### ISSUE TITLE
ZBX_NOTSUPPORTED: Cannot create /var/run/netns

### ISSUE THREAD

**Issue by jc36** [monitoringartist/zabbix-docker-monitoring#103]
I used the AllowRoot=1 option and checked that inside the container it was added to zabbix_agentd.conf:

$ docker run  --restart=always --name=zabbix-agent-xxl -h $(hostname) -p 10050:10050 -v /:/rootfs -v /var/run:/var/run -e "ZA_Server=10.xx.xx.xx" -e "AllowRoot=1" -d monitoringartist/zabbix-agent-xxl-limited:latest

$ docker cp zabbix-agent-xxl:/etc/zabbix/zabbix_agentd.conf  -|grep -a AllowRoot
AllowRoot=1 #output

After that I get the same error "Cannot create /var/run/netns"

**Comment by jangaraj** [comment]
Please use dockbix agent image and read readme for configuration options - https://github.com/monitoringartist/dockbix-agent-xxl
