### ISSUE TITLE
docker.info metrics

### ISSUE THREAD

**Issue by thefactor82** [monitoringartist/zabbix-docker-monitoring#104]
Sorry for bothering you, but I'm not finding a way to fully use docker.info metrics for my docker host monitored by zabbix.
I can do correctly
zabbix_get -s myhostname -k docker.info["NCPU"]
or
zabbix_get -s myhostname -k docker.info["Containers"]

but if I want to get the others infos such Data space available, or how many running, paused and stopped containers, what parameter I have to use with docker.info[] key?

I cannot find a lists of usable parameters

Thanks in advance

**Comment by jangaraj** [comment]
There are no hardcoded parameters. They depend on your Docker API and information, which are available from `/info` endpoint.

https://docs.docker.com/engine/api/v1.37/#operation/SystemInfo

```
{
    "ID": "7TRN:IPZB:QYBB:VPBQ:UMPP:KARE:6ZNR:XE6T:7EWV:PKF4:ZOJD:TPYS",
    "Containers": 14,
    "ContainersRunning": 3,
    "ContainersPaused": 1,
    "ContainersStopped": 10,
    "Images": 508,
    "Driver": "overlay2",
....
```
Zabbix `docker.info` parameter must be available as key in the returned json. For example you want to read value `ContainersRunning` -> docker.info["ContainersRunning"], etc.
