### ISSUE TITLE
Full permission

### ISSUE THREAD

**Issue by SrMouraSilva** [monitoringartist/zabbix-docker-monitoring#105]
Hello, is this permission really necessary? Access to "/" as read and write?

```
  -v /:/rootfs \
  -v /var/run:/var/run \
```

**Comment by jangaraj** [comment]
Actually it's not necessary, but it is simplifying documentation. Otherwise there will be a few different run commands for different operation systems.

**Comment by jangaraj** [comment]
The fastest way is to test it. There are implemented checks, which may stop your invalid attempt. 

Anyway, rw permission is required at least for docker socket, otherwise module won't be able to get some details/metrics.
