### ISSUE TITLE
Cannot open metric file, Zabbix Agent 4.0

### ISSUE THREAD

**Issue by andrin55** [monitoringartist/zabbix-docker-monitoring#106]
Hello

I've compiled your zabbix_module_docker.so with the new 4.0 LTS build. Sadly the module doesn't seem to get the paths right:
```
Cannot open metric file: '/sys/fs/cgroup/memory/system.slice/docker-/3d15b28efe44.scope/memory.stat'
Cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/system.slice/docker-/3d15b28efe44.scope/cpuacct.stat'
```

The right path should be:
```
[root@docker01 ~]# cat /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-3d15b28efe44ba23b9c0541e35417c2ccc280e9b1f5d2a07dbf2880e08944234.scope/cpuacct.stat
user 1396
system 2958
```

My docker version is 1.13.1 and its running on Centos 7. I used svn://svn.zabbix.com/tags/4.0.0 to compile it for the agent 4.0.0.

Thank you

**Comment by jangaraj** [comment]
Check startup logs. I guess you didn't add additional permissions, because short container id is used, so module is not able to use docker API.

**Comment by andrin55** [comment]
I changed the ownership of the docker socket with the "group" directive in /etc/docker/daemon.json. I am now able to query the containers via the zabbix user with curl:
```
[root@docker01 ~]# sudo -u zabbix curl --unix-socket /var/run/docker.sock --no-buffer -XGET v1.24/containers/json?all=0
[{"Id":"3d15b28efe44ba23b9c0541e35417c2ccc280e9b1f5d2a07dbf2880e08944234","Names"....
```

The agent logs shows now a different, also wrong path:
```
Starting Zabbix Agent [Docker01]. Zabbix 4.0.0 (revision 85308).
**** Enabled features ****
IPv6 support:          YES
TLS support:           YES
**************************
using configuration file: /etc/zabbix/zabbix_agentd.conf
loaded modules: zabbix_module_docker.so
agent #0 started [main process]
agent #1 started [collector]
agent #2 started [listener #1]
agent #6 started [active checks #2]
agent #3 started [listener #2]
agent #4 started [listener #3]
agent #5 started [active checks #1]
Cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/system.slice//container_name/cpuacct.stat'
Cannot open metric file: '/sys/fs/cgroup/memory/system.slice//container_name/memory.stat'

```

It now uses the container name instead of the ID. 

The module only works on my host when used with the AllowRoot=1 option, which I very much want to avoid.

**Comment by jangaraj** [comment]
Please increase log level and delete monitored host from Zabbix server, so it won't use previously discovered items.

**Comment by andrin55** [comment]
The full log is pretty huge, but here's the interesting part:
```
Zabbix Agent stopped. Zabbix 4.0.0 (revision 85308).
Starting Zabbix Agent [Docker01]. Zabbix 4.0.0 (revision 85308).
**** Enabled features ****
IPv6 support:          YES
TLS support:           YES
**************************
using configuration file: /etc/zabbix/zabbix_agentd.conf
In zbx_load_modules()
loading module "/usr/local/lib/zabbix/agent//zabbix_module_docker.so"
In zbx_module_api_version()
In zbx_module_init()
zabbix_module_docker v0.6.9, compilation time: Oct 24 2018 12:05:23
In zbx_docker_dir_detect()
Detected docker stat directory: /sys/fs/cgroup/
Detected used docker driver dir: system.slice/
Detected systemd docker - prefix/suffix will be used
Detected JoinController cpu,cpuacct
In zbx_docker_api_detect()
In zbx_docker_perm()
Additional permission of Zabbix Agent are not detected - only basic docker metrics are available
In zbx_module_item_list()
In zbx_module_item_timeout()
cannot find "zbx_module_history_write_cbs()" function in module "zabbix_module_docker.so": /usr/local/lib/zabbix/agent//zabbix_module_docker.so: undefined symbol: zbx_module_history_write_cbs
loaded modules: zabbix_module_docker.so
End of zbx_load_modules():SUCCEED
In init_collector_data()
In zbx_dshm_create() size:0
End of zbx_dshm_create():SUCCEED shmid:-1
End of init_collector_data()
agent #0 started [main process]
agent #2 started [listener #1]
In zbx_tls_init_child()
agent #6 started [active checks #2]
In zbx_tls_init_child()
OpenSSL library (version OpenSSL 1.0.1e-fips 11 Feb 2013) initialized
....
__zbx_zbx_setproctitle() title:'listener #3 [processing request]'
Requested [docker.up[/3d15b28efe44]]
In zbx_module_docker_up()
In zbx_module_docker_get_fci()
Translating container name to fci by using docker.inspect
In zbx_module_docker_inspect_exec()
In zbx_docker_api_detect()
In zbx_docker_perm()
Additional permission of Zabbix Agent are not detected - only basic docker metrics are available
Docker's socket API is not available
Default fci will be used, because zbx_module_docker_inspect_exec FAIL: Docker's socket API is not available
Metric source file: /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-/3d15b28efe44.scope/cpuacct.stat
Cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/system.slice/docker-/3d15b28efe44.scope/cpuacct.stat', container doesn't run
Sending back [0]
__zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
```

**Comment by jangaraj** [comment]
> Additional permission of Zabbix Agent are not detected - only basic docker metrics are available

https://github.com/monitoringartist/zabbix-docker-monitoring/blob/27709c75b74e6404295b5b56b846b4e3b6d8f982/src/modules/zabbix_module_docker/zabbix_module_docker.c#L305-L317

=> module didn't get correct anwser for Docker API `/ping` request. You have still problem with permissions for the socket

Did you follow readme: https://github.com/monitoringartist/zabbix-docker-monitoring#additional-docker-permissions ?

**Comment by jangaraj** [comment]
Please provide a full log if you need help https://github.com/monitoringartist/zabbix-docker-monitoring#troubleshooting

**Comment by andrin55** [comment]
[zabbix_agentd.log](https://github.com/monitoringartist/zabbix-docker-monitoring/files/2511927/zabbix_agentd.log)
There is my log.

**Comment by andrin55** [comment]
The "dockerroot" group came with my distributions standard installation of docker (Centos 7)
`dockerroot:x:997:994:Docker User:/var/lib/docker:/sbin/nologin`

After changing the group to "docker" the module was able to get permissions and worked correctly:
zabbix agent user has docker perm
In zbx_module_docker_socket_query()
Docker's socket query: GET /_ping HTTP/1.0
Docker's socket response: OK
Docker's socket works - extended docker metrics are available

Thank you for your support.

**Comment by jangaraj** [comment]
I guess you have some customised docker package. [Standard Docker - CE package](https://docs.docker.com/install/linux/docker-ce/centos/) (current docker-ce-18.06.1.ce-3.el7.x86_64) uses `docker` group.

**Comment by andrin55** [comment]
I'm using the one from RedHat/Centos:
```
Installed Packages
Name        : docker
Arch        : x86_64
Epoch       : 2
Version     : 1.13.1
Release     : 75.git8633870.el7.centos
Size        : 57 M
Repo        : installed
From repo   : extras
```
