### ISSUE TITLE
No discovering lxc and systemd-spawn containers

### ISSUE THREAD

**Issue by StonedAstronaut** [monitoringartist/zabbix-docker-monitoring#107]
I use ubuntu 16.04, zabbix-agent 3.4.14 with loadable module ([precompiled](https://github.com/monitoringartist/zabbix-docker-monitoring/raw/gh-pages/ubuntu16/3.4/zabbix_module_docker.so) and manual compiled) with [Zabbix-Template-App-Docker.xml](https://raw.githubusercontent.com/monitoringartist/zabbix-docker-monitoring/master/template/Zabbix-Template-App-Docker.xml) at host system. Also I configure all docker additional permissions. On host machine I use lxd, docker and systemd(only for test LLD) containers. Zabbix with loadable module discover only docker containers. My C language knoledge is poor, like English as well 😸 , but I found "lxc" at source code:

```
char *drivers[] = {
            "docker/",        // Non-systemd Docker: docker -d -e native
            "system.slice/",  // Systemd Docker
            "lxc/",           // Non-systemd LXC: docker -d -e lxc
            "libvirt/lxc/",   // Legacy libvirt-lxc
            // TODO pos = cgroup.find("-lxc\\x2");     // Systemd libvirt-lxc
            // TODO pos = cgroup.find(".libvirt-lxc"); // Non-systemd libvirt-lxc
            ""
        }, **tdriver;
```

As I understand `"docker/"`, `"system.slice/"`, `"lxc/"` are parts of `/sys/fs/cgroup/` path.

At `DebugLevel=4` zabbix agent log `Metric source file:` only from `/sys/fs/cgroup/*/docker/`.

Pls help, what i'm doing wrong?

**Comment by jangaraj** [comment]
You are running Docker **and** LXC containers. The module is designated only for one type of containers, . Docker container path is discovered first, so module will monitor only Docker containers. You can't discover/monitor both container types on the host.
