### ISSUE TITLE
How to solve this problem？

### ISSUE THREAD

**Issue by 744132849** [monitoringartist/zabbix-docker-monitoring#108]
15949:20181109:091234.900 Cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/docker//ae22f78d8c78/cpuacct.stat'
 15950:20181109:091235.901 Cannot open metric file: '/sys/fs/cgroup/memory/docker//5c0394f7f61b/memory.stat'
 15949:20181109:091236.902 Cannot open metric file: '/sys/fs/cgroup/memory/docker//ae22f78d8c78/memory.stat'
 15950:20181109:091237.902 Cannot open metric file: '/sys/fs/cgroup/memory/docker//5c0394f7f61b/memory.stat'
 15951:20181109:091238.904 Cannot open metric file: '/sys/fs/cgroup/memory/docker//ae22f78d8c78/memory.stat'
 15950:20181109:091239.905 Cannot open metric file: '/sys/fs/cgroup/memory/docker//5c0394f7f61b/memory.stat'
 15951:20181109:091240.906 Cannot open metric file: '/sys/fs/cgroup/memory/docker//ae22f78d8c78/memory.stat'
 15950:20181109:092234.203 Cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/docker//5c0394f7f61b/cpuacct.stat'
 15949:20181109:092235.205 Cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/docker//ae22f78d8c78/cpuacct.stat'
 15950:20181109:092236.205 Cannot open metric file: '/sys/fs/cgroup/memory/docker//5c0394f7f61b/memory.stat'
 15949:20181109:092237.207 Cannot open metric file: '/sys/fs/cgroup/memory/docker//ae22f78d8c78/memory.stat'
 15950:20181109:092238.207 Cannot open metric file: '/sys/fs/cgroup/memory/docker//5c0394f7f61b/memory.stat'
 15949:20181109:092239.209 Cannot open metric file: '/sys/fs/cgroup/memory/docker//ae22f78d8c78/memory.stat'
 15950:20181109:092240.210 Cannot open metric file: '/sys/fs/cgroup/memory/docker//5c0394f7f61b/memory.stat'
 15951:20181109:092241.211 Cannot open metric file: '/sys/fs/cgroup/memory/docker//ae22f78d8c78/memory.stat'
 15950:20181109:093233.341 Cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/docker//5c0394f7f61b/cpuacct.stat'
 15951:20181109:093234.344 Cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/docker//ae22f78d8c78/cpuacct.stat'
 15949:20181109:093235.345 Cannot open metric file: '/sys/fs/cgroup/memory/docker//5c0394f7f61b/memory.stat'

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/zabbix-docker-monitoring/blob/master/README.md#additional-docker-permissions
