### ISSUE TITLE
cannot load module

### ISSUE THREAD

**Issue by HattabbI4** [monitoringartist/zabbix-docker-monitoring#109]
### Hello! 
I have a problem:

> In zbx_load_modules()
> loading module "/usr/src/zabbix/src/modules/zabbix_module_docker/zabbix_module_docker.so"
> cannot load module "zabbix_module_docker.so": /usr/src/zabbix/src/modules/zabbix_module_docker/zabbix_module_docker.so: undefined symbol: del_zeroes
> End of zbx_load_modules():FAIL
> loading modules failed, exiting...
> 

Compiled module in manual, below listing
[zabbix_list.txt](https://github.com/monitoringartist/zabbix-docker-monitoring/files/2588572/zabbix_list.txt)

> zabbix_agentd (daemon) (Zabbix) 4.0.1
> CentOS Linux release 7.5.1804 (Core) 
>GNU Make 3.82

Thanks!

**Comment by jangaraj** [comment]
You have used 3.2.7 source code for compilation and 4.0.1 for module run. Used versions must be the same in both cases.

**Comment by HattabbI4** [comment]
Oh! I'm sorry...
