### ISSUE TITLE
HCONTAINERID

### ISSUE THREAD

**Issue by arz-GW** [monitoringartist/zabbix-docker-monitoring#111]
My system is centos7, and the 'HCONTAINERID' I want to get is the character village before the underline.

Now:
[root@zabbix ~]#  zabbix_get -s  10.19.82.227  -k docker.discovery
{"data":[{"{#FCONTAINERID}":"4fa5c170f5d05c7128d02c17a90eb35ec4ae575b386a4a33b0ebd9d0e0287502","{#SCONTAINERID}":"4fa5c170f5d0","{#SYSTEM.HOSTNAME}":"10-19-82-227","{#HCONTAINERID}":"test-jkb-portal_jkb-portal.1.4k6ga09m3b6byht4ks69afop8"}

after:
[root@zabbix ~]#  zabbix_get -s  10.19.82.227  -k docker.discovery
{"data":[{"{#FCONTAINERID}":"4fa5c170f5d05c7128d02c17a90eb35ec4ae575b386a4a33b0ebd9d0e0287502","{#SCONTAINERID}":"4fa5c170f5d0","{#SYSTEM.HOSTNAME}":"10-19-82-227","{#HCONTAINERID}":"test-jkb-portal"}

**Comment by arz-GW** [comment]
Thank you very much.

**Comment by jangaraj** [comment]
That is not possible. You will need to implement your own discovery if you really need it.
