### ISSUE TITLE
Zabbix agent 4.0.3 doesn't start with this module

### ISSUE THREAD

**Issue by thefactor82** [monitoringartist/zabbix-docker-monitoring#112]
cannot load module "zabbix_module_docker.so": /usr/lib64/zabbix/modules/zabbix_module_docker.so: undefined symbol: del_zeroes

Starting Zabbix Agent [trr-cnhds-lp9]. Zabbix 4.0.3 (revision 87993)

:-(

**Comment by jangaraj** [comment]
You need to compile your own 4.0.3 module version - https://github.com/monitoringartist/zabbix-docker-monitoring#compilation
