### ISSUE TITLE
Zabbix agent 4.0.6 crash with compiled module

### ISSUE THREAD

**Issue by Makubo** [monitoringartist/zabbix-docker-monitoring#119]
I compiled module with zabbix 4.0.6 version. Compilation was without problems, but zabbix agent is crash on start. I attach my compile action log and zabbix-agent log.

[compile_actions.txt](https://github.com/monitoringartist/zabbix-docker-monitoring/files/3083537/compile_actions.txt)
[zabbix_agentd.log](https://github.com/monitoringartist/zabbix-docker-monitoring/files/3083538/zabbix_agentd.log)

**Comment by jangaraj** [comment]
Did you copy `/usr/lib/zabbix/modules/zabbix_module_docker.so` from `/usr/src/zabbix/src/modules/zabbix_module_docker/zabbix_module_docker.so`?

**Comment by Makubo** [comment]
Oh, thanks. I am very ashamed. It was my falt. I puted it in /var/lib/zabbix... not in /usr/lib/zabbix...
