### ISSUE TITLE
zabbix_module_docker.so: undefined symbol: del_zeroes - v4.0.4

### ISSUE THREAD

**Issue by gferandelle** [monitoringartist/zabbix-docker-monitoring#122]
I compiled the module for version v4.0.4 using the DockerFile with "ENV ZABBIX_VERSION=tags/4.0.4" with debian:stretch base image.

But I still have the following error 
```
216141:20190516:174452.688 cannot load module "zabbix_module_docker.so": /usr/lib/zabbix/modules/zabbix_module_docker.so: undefined symbol: del_zeroes
216141:20190516:174452.688 loading modules failed, exiting...
```

**Comment by jangaraj** [comment]
Which OS and zabbix agent version are you using?

**Comment by gferandelle** [comment]
The agent (v4.04) run on debian stretch

**Comment by jangaraj** [comment]
Could you provide agent logs, please? How did you install agent?

**Comment by gferandelle** [comment]
Thanks for your reply
Agent logs : 

> 204311:20190517:090417.439 Starting Zabbix Agent [lys-hub1-srv1.lys.stanley-robotics.site]. Zabbix 4.0.4 (revision 89349).
> 204311:20190517:090417.439 **** Enabled features ****
> 204311:20190517:090417.439 IPv6 support:          YES
> 204311:20190517:090417.439 TLS support:           YES
> 204311:20190517:090417.439 **************************
> 204311:20190517:090417.439 using configuration file: /etc/zabbix/zabbix_agentd.conf
> 204311:20190517:090417.439 In zbx_load_modules()
> 204311:20190517:090417.439 loading module "/usr/lib/zabbix/modules/libzbxpgsql.so"
> 204311:20190517:090417.440 starting agent module libzbxpgsql 1.1.0
> 204311:20190517:090417.440 using module configuration file: /etc/zabbix/libzbxpgsql.conf
> 204311:20190517:090417.441 loading module "/usr/lib/zabbix/modules/zabbix_module_docker.so"
> 204311:20190517:090417.441 cannot load module "zabbix_module_docker.so": /usr/lib/zabbix/modules/zabbix_module_docker.so: undefined symbol: del_zeroes
> 204311:20190517:090417.441 End of zbx_load_modules():FAIL
> 204311:20190517:090417.441 loading modules failed, exiting...

The agent was installed using this repo : "http://repo.zabbix.com/zabbix/4.0/debian stretch/main amd64 Packages"

**Comment by jangaraj** [comment]
Please compile also your agent. You will prove that problem is not in the agent. Maybe installed agent is compiled statically.

**Comment by gferandelle** [comment]
Same result.

**Comment by gferandelle** [comment]
I upgraded the agent to 4.0.7 and recompiled the module. Now it is work.

**Comment by jangaraj** [comment]
Thank you for the info. Probably there is some agent version mismatch. Tested in the build container and it works there:
```
   129:20190517:171447.511 Starting Zabbix Agent [Zabbix server]. Zabbix 4.0.4 (revision {ZABBIX_REVISION}).
   129:20190517:171447.512 **** Enabled features ****
   129:20190517:171447.512 IPv6 support:           NO
   129:20190517:171447.512 TLS support:            NO
   129:20190517:171447.512 **************************
   129:20190517:171447.512 using configuration file: /usr/local/etc/zabbix_agentd.conf
   129:20190517:171447.512 In zbx_load_modules()
   129:20190517:171447.512 loading module "/root/zabbix/src/modules/zabbix_module_docker/zabbix_module_docker.so"
   129:20190517:171447.512 In zbx_module_api_version()
   129:20190517:171447.512 In zbx_module_init()
   129:20190517:171447.512 zabbix_module_docker v0.6.9, compilation time: May 17 2019 17:02:02
   129:20190517:171447.512 In zbx_docker_dir_detect()
   129:20190517:171447.513 Detected docker stat directory: /sys/fs/cgroup/
   129:20190517:171447.513 Cannot detect used docker driver
   129:20190517:171447.513 In zbx_docker_api_detect()
   129:20190517:171447.513 In zbx_module_docker_socket_query()
   129:20190517:171447.513 Cannot connect to standard docker's socket /var/run/docker.sock
   129:20190517:171447.514 Docker's socket doesn't work - only basic docker metrics are available
   129:20190517:171447.514 In zbx_module_item_list()
   129:20190517:171447.514 In zbx_module_item_timeout()
   129:20190517:171447.514 cannot find "zbx_module_history_write_cbs()" function in module "zabbix_module_docker.so": /root/zabbix/src/modules/zabbix_module_docker/zabbix_module_docker.so: undefined symbol: zbx_module_history_write_cbs
   129:20190517:171447.514 loaded modules: zabbix_module_docker.so
   129:20190517:171447.514 End of zbx_load_modules():SUCCEED
```
