### ISSUE TITLE
Is there any guide to calculate what CPU metric I need to set for 4 or 8 CPUs?

### ISSUE THREAD

**Issue by ChuckB0ris** [monitoringartist/zabbix-docker-monitoring#130]
docker.cpu[cid,cmetric] | CPU metrics:cmetric - any available CPU metric in the pseudo-file cpuacct.stat/cpu.stat, e.g.: system, user, total (current sum of system/user or container throttling metrics: nr_throttled, throttled_timeNote: CPU user/system/total metrics must be recalculated to % utilization value by Zabbix - Delta (speed per second).
-- | --

Default is 2500

**Comment by jangaraj** [comment]
I'm not sure what do you need. RAW metric can be 2500 (counter of used CPU jiffies), but it will be recalculated to % by Zabbix server - see configuration of item in the template.

**Comment by ChuckB0ris** [comment]
I mean how can I calculate "RAW metric" of whatever I need to put in the trigger, for example if I got 8 core CPUs and want to trigger alert when at >90% all cores/threads? Will it be the same value for a server with less CPUs? I do not understand the formula I need to use to calculate these :).

Thanks for the help Jangaraj.

**Comment by jangaraj** [comment]
Please use provided template. There is calculated normalized CPU utilization, so you really don't need to consider any CPU count.
