### ISSUE TITLE
Cannot find a line with requested metric in cpuacct.stat file

### ISSUE THREAD

**Issue by thakuranand34** [monitoringartist/zabbix-docker-monitoring#131]
Hi Team,

I have zabbix-agent container is up and running.I want to monitor Docker CPU utilization through zabbix server.but, no luck.Please find below attached error for your reference.Kindly suggest resolution for this issue.Thanks in advance.
![error in docker cpu monitoring](https://user-images.githubusercontent.com/25495617/60265407-4bf7e680-9903-11e9-929b-a256893e78f4.png)

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/zabbix-docker-monitoring#troubleshooting

**Comment by jangaraj** [comment]
I'm closing this one, because logs are not provided.
