### ISSUE TITLE
Intergation zabbix_module_docker with debian 10

### ISSUE THREAD

**Issue by qukly** [monitoringartist/zabbix-docker-monitoring#132]
Hello, we use your module for our docker hosts. But will you provide compatibility zabbix_module_docker with Debian 10? Thank you

**Comment by jangaraj** [comment]
What is a problem? Did you compile module for Debian 10?

**Comment by qukly** [comment]
no, I don't know how to compile the module. Current module for Debian 9 doesn't work
"cannot load module "zabbix_module_docker.so": /usr/local/lib/zabbix/agent//zabbix_module_docker.so: undefined symbol: del_zeroes"

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/zabbix-docker-monitoring#compilation
