### ISSUE TITLE
Raw data collection only every 30 min?

### ISSUE THREAD

**Issue by drexlma** [monitoringartist/zabbix-docker-monitoring#134]
I installed the standard Docker container. Mysql and Nginx template activated. It only gets the RAW information every 30 minutes.

Zabbix-Server: 8 Core, Debian 10
Hosts: 2 (Zabbix + 1 Server)

![chart_mysql](https://user-images.githubusercontent.com/7121202/70860363-1a122500-1f21-11ea-8774-dcb6f89cdd1a.jpg)

**Comment by jangaraj** [comment]
Sorry, it is not clear what are you asking for and how it is related to this project?

**Comment by jangaraj** [comment]
Closing, because it out of the scope and author opened this question in another repo as well.
For the record: https://github.com/zabbix/zabbix-docker/issues/528
