### ISSUE TITLE
 How can this be used in detail?

### ISSUE THREAD

**Issue by wujunlin555** [monitoringartist/zabbix-docker-monitoring#138]
docker.stats[cid,par1,<par2>,<par3>]   part1 part2 part3   How to write

**Comment by jangaraj** [comment]
Please read readme https://github.com/monitoringartist/zabbix-docker-monitoring. You have examples there:

> For example:
> docker.stats[cid,memory_stats,usage], docker.stats[cid,network,rx_bytes], docker.stats[cid,cpu_stats,cpu_usage,total_usage]
