### ISSUE TITLE
Swarm manager support?

### ISSUE THREAD

**Issue by thetuxinator** [monitoringartist/zabbix-docker-monitoring#140]
Hi,

Can this support a "swarm manager" ?

kind regards

Tuxinator

**Comment by jangaraj** [comment]
In theory yes, but IMHO it isn't in the scope of this project: container monitoring. All container orchestrations (Swarm, Kubernetes, Rancher, Nomad, AWS ECS, ....) work on top of container, but they have own service entities. So this project can provide low level container metrics, but you will need to aggregate them to the service metrics based on orchestration tool.
