### ISSUE TITLE
Cannot display container name in zabbix

### ISSUE THREAD

**Issue by ScorpioJipson** [monitoringartist/zabbix-docker-monitoring#141]
In zabbix, it can only be displayed by the container id, such as {#HCONTAINERID}, variable without container name
I hope to display the container name in the dashboard and the container name in the alarm
thanks

**Comment by jangaraj** [comment]
You need to modify your discovery rule and use proper macro:
```
{#FCONTAINERID} - full container ID (64 character string)
{#SCONTAINERID} - short container ID (12 character string)
{#HCONTAINERID} - human name of the container
```
