### ISSUE TITLE
Unsupported item key

### ISSUE THREAD

**Issue by Szymon-Rysztof** [monitoringartist/zabbix-docker-monitoring#142]
Hello, 
im trying to load compiled module to Zabbix Agent 4.0.4, 
i compiled module with provided instruction, loaded it into zabbix agent, but im still getting error: 
`active check "docker.containers.discovery" is not supported: Unsupported item key.`

also there is 
`loaded modules: zabbix_module_docker.so`
in log, so im sure, that module is loaded, any suggestions? 

I compiled on 
`**uname -a** 
Linux pop-os 5.4.0-7625-generic #29~1587437458~20.04~2960161-Ubuntu SMP Tue Apr 21 05:16:44 UTC  x86_64 x86_64 x86_64 GNU/Linux` 
`**cat /etc/os-release**
NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
`
and tried to use it on 
`**uname -a** 
Linux [HOSTNAME] 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
`
`**cat /etc/os-release**
NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
`

**Comment by jangaraj** [comment]
This module doesn't offer `docker.containers.discovery` key. That is from recent official Zabbix Docker integration. This module offers `docker.discovery[<par1>,<par2>,<par3>]` key.
