### ISSUE TITLE
 cannot load module "zabbix_module_docker.so"

### ISSUE THREAD

**Issue by gabricar** [monitoringartist/zabbix-docker-monitoring#145]
After compiling the module for Zabbix 4.0.0 I get this error on the agent statup

  3740:20200720:165839.917 cannot load module "zabbix_module_docker.so": /usr/src/zabbix/src/modules/zabbix_module_docker/zabbix_module_docker.so: undefined symbol: __zbx_zbx_snprintf
  3740:20200720:165839.918 loading modules failed, exiting...
  3740:20200720:165839.918 Zabbix Agent stopped. Zabbix 4.0.22 (revision 073cb9f4f6).

compiled using
 git clone -b 4.0.0 --depth 1 https://github.com/zabbix/zabbix.git /usr/src/zabbix
 cd /usr/src/zabbix
 ./bootstrap.sh
 ./configure --enable-agent
 mkdir src/modules/zabbix_module_docker
 cd src/modules/zabbix_module_docker
 wget https://raw.githubusercontent.com/monitoringartist/zabbix-docker-monitoring/master/src/modules/zabbix_module_docker/zabbix_module_docker.c
 wget https://raw.githubusercontent.com/monitoringartist/zabbix-docker-monitoring/master/src/modules/zabbix_module_docker/Makefile
 make

**Comment by gabricar** [comment]
I've also tried to use the tag 4.0.22 but this one does not compile at all

gcc -fPIC -shared -o zabbix_module_docker.so zabbix_module_docker.c -I../../../include -I../../../src/libs/zbxsysinfo
zabbix_module_docker.c: In function ‘zbx_module_docker_inspect_exec’:
zabbix_module_docker.c:385:13: error: too few arguments to function ‘zbx_json_value_by_name’
             if (SUCCEED != zbx_json_value_by_name(&jp_data, param1, api_value, buffer_size))
             ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c:402:25: error: too few arguments to function ‘zbx_json_value_by_name’
                         if (SUCCEED != zbx_json_value_by_name(&jp_data2, param2, api_value2, buffer_size))
                         ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c:486:32: error: too few arguments to function ‘zbx_json_value_by_name’
                                if (SUCCEED != zbx_json_value_by_name(&jp_data3, param3, api_value3, buffer_size))
                                ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c: In function ‘zbx_module_docker_port_discovery’:
zabbix_module_docker.c:555:3: error: too few arguments to function ‘add_request_param’
   add_request_param(&request2, zbx_strdup(NULL, container));
   ^
In file included from zabbix_module_docker.c:38:0:
../../../src/libs/zbxsysinfo/sysinfo.c:342:13: note: declared here
 static void add_request_param(AGENT_REQUEST *request, char *pvalue, zbx_request_parameter_type_t type)
             ^
zabbix_module_docker.c:556:3: error: too few arguments to function ‘add_request_param’
   add_request_param(&request2, zbx_strdup(NULL, "HostConfig"));
   ^
In file included from zabbix_module_docker.c:38:0:
../../../src/libs/zbxsysinfo/sysinfo.c:342:13: note: declared here
 static void add_request_param(AGENT_REQUEST *request, char *pvalue, zbx_request_parameter_type_t type)
             ^
zabbix_module_docker.c:557:3: error: too few arguments to function ‘add_request_param’
   add_request_param(&request2, zbx_strdup(NULL, "PortBindings"));
   ^
In file included from zabbix_module_docker.c:38:0:
../../../src/libs/zbxsysinfo/sysinfo.c:342:13: note: declared here
 static void add_request_param(AGENT_REQUEST *request, char *pvalue, zbx_request_parameter_type_t type)
             ^
zabbix_module_docker.c:611:5: error: too few arguments to function ‘zbx_json_value_by_name’
     if (FAIL == zbx_json_value_by_name(&jp_obj, "HostPort", host_port, sizeof(host_port))) {
     ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c: In function ‘zbx_module_docker_get_fci’:
zabbix_module_docker.c:654:9: error: too few arguments to function ‘add_request_param’
         add_request_param(&request, zbx_strdup(NULL, fci));
         ^
In file included from zabbix_module_docker.c:38:0:
../../../src/libs/zbxsysinfo/sysinfo.c:342:13: note: declared here
 static void add_request_param(AGENT_REQUEST *request, char *pvalue, zbx_request_parameter_type_t type)
             ^
zabbix_module_docker.c:655:9: error: too few arguments to function ‘add_request_param’
         add_request_param(&request, zbx_strdup(NULL, "Id"));
         ^
In file included from zabbix_module_docker.c:38:0:
../../../src/libs/zbxsysinfo/sysinfo.c:342:13: note: declared here
 static void add_request_param(AGENT_REQUEST *request, char *pvalue, zbx_request_parameter_type_t type)
             ^
zabbix_module_docker.c: In function ‘zbx_module_docker_discovery_extended’:
zabbix_module_docker.c:1795:17: error: too few arguments to function ‘zbx_json_value_by_name’
                 if (SUCCEED != zbx_json_value_by_name(&jp_row, "Id", cid, cid_length))
                 ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c:1812:21: error: too few arguments to function ‘add_request_param’
                     add_request_param(&request2, zbx_strdup(NULL, cid));
                     ^
In file included from zabbix_module_docker.c:38:0:
../../../src/libs/zbxsysinfo/sysinfo.c:342:13: note: declared here
 static void add_request_param(AGENT_REQUEST *request, char *pvalue, zbx_request_parameter_type_t type)
             ^
zabbix_module_docker.c:1817:24: error: too few arguments to function ‘add_request_param’
                        add_request_param(&request2, zbx_strdup(NULL, (request)->params[n]));
                        ^
In file included from zabbix_module_docker.c:38:0:
../../../src/libs/zbxsysinfo/sysinfo.c:342:13: note: declared here
 static void add_request_param(AGENT_REQUEST *request, char *pvalue, zbx_request_parameter_type_t type)
             ^
zabbix_module_docker.c: In function ‘zbx_module_docker_info’:
zabbix_module_docker.c:1955:9: error: too few arguments to function ‘zbx_json_value_by_name’
         if (SUCCEED != zbx_json_value_by_name(&jp_data, info, api_value, buffer_size))
         ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c: In function ‘zbx_module_docker_stats’:
zabbix_module_docker.c:2032:13: error: too few arguments to function ‘zbx_json_value_by_name’
             if (SUCCEED != zbx_json_value_by_name(&jp_data, param1, api_value, buffer_size))
             ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c:2047:25: error: too few arguments to function ‘zbx_json_value_by_name’
                         if (SUCCEED != zbx_json_value_by_name(&jp_data2, param2, api_value2, buffer_size))
                         ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c:2062:37: error: too few arguments to function ‘zbx_json_value_by_name’
                                     if (SUCCEED != zbx_json_value_by_name(&jp_data3, param3, api_value3, buffer_size))
                                     ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c: In function ‘zbx_module_docker_cstatus’:
zabbix_module_docker.c:2244:25: error: too few arguments to function ‘zbx_json_value_by_name’
                         if (SUCCEED != zbx_json_value_by_name(&jp_row, "Status", status, cid_length))
                         ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
zabbix_module_docker.c:2326:33: error: too few arguments to function ‘zbx_json_value_by_name’
                                 if (SUCCEED != zbx_json_value_by_name(&jp_row, "Status", status, cid_length))
                                 ^
In file included from zabbix_module_docker.c:25:0:
../../../include/zbxjson.h:196:6: note: declared here
 int  zbx_json_value_by_name(const struct zbx_json_parse *jp, const char *name, char *string, size_t len,
      ^
make: *** [zabbix_module_docker] Error 1

**Comment by jangaraj** [comment]
I would try to compile against your exact agent version (`4.0.22` - compilation against 4.0.0 and then loading to agent 4.0.22 may not work as you see). But keep in mind there is breaking change in used internal function zbx_json* https://github.com/monitoringartist/zabbix-docker-monitoring/issues/133

**Comment by gabricar** [comment]
I was able to build 4.0.12 but now I see different issues when it tries to collect the items. It is looking into the wrong path and has a square where should be the container name. Not sure what is going on. I already add the root permissions to the agent.conf

 20281:20200720:172124.147 Cannot find the [Id] item in the received JSON object
 20281:20200720:172124.147 Cannot open metric file: '/sys/fs/cgroup/memory/docker///memory.stat'
 20282:20200720:172124.147 Cannot find the [Id] item in the received JSON object
 20282:20200720:172124.147 Cannot open metric file: '/sys/fs/cgroup/memory/docker///memory.stat'
 20282:20200720:172124.147 Cannot find the [Id] item in the received JSON object
 20282:20200720:172124.147 Cannot open metric file: '/sys/fs/cgroup/memory/docker///memory.stat'
 20281:20200720:172124.147 Cannot find the [Id] item in the received JSON object
 20281:20200720:172124.147 Cannot open metric file: '/sys/fs/cgroup/memory/docker//veeam-office-365-portal_thinkon_/memory.stat'
 20283:20200720:172124.147 Cannot find the [Id] item in the received JSON object
 20283:20200720:172124.147 Cannot open metric file: '/sys/fs/cgroup/memory/docker//veeam-office-365-portal_thinkon_/memory.stat'

**Comment by i-ky** [comment]
You should downgrade agent as well.

**Comment by gabricar** [comment]
I'll give it a try

**Comment by gabricar** [comment]
It works... but please let me know if you are able to compile the 4.0.22

**Comment by i-ky** [comment]
I guess this should be covered by #133.

**Comment by jangaraj** [comment]
Compilation now works for 5.2/5.0/4.0.
