### ISSUE TITLE
Not Discovering LXC containers

### ISSUE THREAD

**Issue by lalitlsg** [monitoringartist/zabbix-docker-monitoring#153]
Setup dockbix agent  and apply template docker app provided by you in zabbix server.
able to discover docker containers but not lxc containers.

**Comment by jangaraj** [comment]
That is correct. Unfortunately, current module design can't detect all types of the containers at the same time. It uses first detected container type, which is `docker` container type in your case.

**Comment by lalitlsg** [comment]
so then will it able to monitor lxc container or not

**Comment by jangaraj** [comment]
Yes, it should (to be honest LXC is not very widely used/tested). Here is is the order of the discovery:

https://github.com/monitoringartist/zabbix-docker-monitoring/blob/ad0f4807b330fb2d227a121e257c3df38ec1010b/src/modules/zabbix_module_docker/zabbix_module_docker.c#L667-L670

Module stops discovering after first match, so if there is just one docker container it will stops there.

**Comment by lalitlsg** [comment]
okk got your point
it means if after creating host and attaching the template in zabbix server
if it discovers the docker containers first the it will not discover the
other type of containers (like lxc)
and after discovering docker containers it will only monitor that
containers from onwards...

thanks for your help!
