### ISSUE TITLE
Cannot collect any data

### ISSUE THREAD

**Issue by pawel-zajac90** [monitoringartist/zabbix-docker-monitoring#156]
Hi,
I've just installed template, and i can't collect any data from docker. The basic data about OS and so on works good, but i've no Docker data....
actually i'm looking in servers logs, and there is a lot of issues with 'unsupported key', not only dockers keys, but also apache and mysql...
Does anybody know how to fix it?

**Comment by jangaraj** [comment]
Installation is not only about template import: https://github.com/monitoringartist/zabbix-docker-monitoring#installation
