### ISSUE TITLE
Error module version 4.0

### ISSUE THREAD

**Issue by Marsanm** [monitoringartist/zabbix-docker-monitoring#160]
Hi, 

I downloaded vesion module for agent 4.0 and when i put in my conf of  zabbix agent and restart service show me an error that cannot load module, what its wrong if i used the module for agent 4.0

**Comment by i-ky** [comment]
Could you copy the exact error message, please?

**Comment by Marsanm** [comment]
Yeah sorry,

This is the message **"cannot load module "zabbix_module_docker.so": /usr/lib/zabbix/modules/zabbix_module_docker.so: undefined symbol: zbx_log_level"**

**Comment by jangaraj** [comment]
Last 4.x Zabbix version is 4.0.27. This version is used in the compilation for published public binaries. There is very likely Zabbix internal code breaking change between 4.0.4 and 4.0.27. You need to compile module on your own for your exact Zabbix agent version to have 100% binary compatibility of the module with the agent - https://github.com/monitoringartist/zabbix-docker-monitoring#compilation .

**Comment by i-ky** [comment]
Module binaries are built with recent Zabbix sources, but 4.0.4 is quite old and, unfortunately, there was a breaking change in Zabbix internal logging API and many modules that were relying on it suffer from incompatibility issues. See [ZBX-10889](https://support.zabbix.com/browse/ZBX-10889) for more information. Can you update Zabbix agent to 4.0.7 or higher as a workaround?

**Comment by i-ky** [comment]
@jangaraj, theoretically, there is [a way](https://github.com/cavaliercoder/libzbxpgsql/pull/142) to fix this, if you are interested.

**Comment by jangaraj** [comment]
Thx, TODO issue created https://github.com/monitoringartist/zabbix-docker-monitoring/issues/161

**Comment by Marsanm** [comment]
Thanks for the info.

Yeah, i compiled my own module with the sources of Zabbix, and works. But i am thinking the best would be update the agent.

Thx!!
