### ISSUE TITLE
zabbix module for 5.2 bug

### ISSUE THREAD

**Issue by eth001** [monitoringartist/zabbix-docker-monitoring#163]
Hi
I am using Zabbix agent 5.2.5 on Ubuntu 18.04
I cannot get docker info from my zabbix agent.
I tried adding zabbix user to docker group without success.
I've downloaded the relative module from : 
https://github.com/monitoringartist/zabbix-docker-monitoring/raw/gh-pages/ubuntu18/5.2/zabbix_module_docker.so
Upon agent loading I get an error message : 

 24012:20210306:023654.796 using configuration file: /etc/zabbix/zabbix_agentd.conf
 24012:20210306:023654.796 In zbx_load_modules()
 24012:20210306:023654.796 loading module "/etc/zabbix/mods/zabbix_module_docker.so"
 24012:20210306:023654.797 In zbx_module_api_version()
 24012:20210306:023654.797 In zbx_module_init()
 24012:20210306:023654.797 zabbix_module_docker v0.7.0, compilation time: Jan  2 2021 18:24:24
 24012:20210306:023654.797 In zbx_docker_dir_detect()
 24012:20210306:023654.797 Detected docker stat directory: /sys/fs/cgroup/
 24012:20210306:023654.797 Detected used docker driver dir: docker/
 24012:20210306:023654.797 Detected JoinController cpu,cpuacct
 24012:20210306:023654.797 In zbx_docker_api_detect()
 24012:20210306:023654.798 In zbx_docker_perm()
 24012:20210306:023654.798 zabbix agent user has docker perm
 24012:20210306:023654.798 In zbx_module_docker_socket_query()
 24012:20210306:023654.798 Docker's socket query: GET /_ping HTTP/1.0
 24012:20210306:023654.799 Docker's socket response: OK
 24012:20210306:023654.800 Docker's socket works - extended docker metrics are available
 24012:20210306:023654.800 In zbx_module_item_list()
 24012:20210306:023654.800 In zbx_module_item_timeout()
 **24012:20210306:023654.800 cannot find "zbx_module_history_write_cbs()" function in module "/etc/zabbix/mods/zabbix_module_docker.so": /etc/zabbix/mods/zabbix_module_docker.so: undefined symbol: zbx_module_history_write_cbs**
 24012:20210306:023654.800 loaded modules: /etc/zabbix/mods/zabbix_module_docker.so
 24012:20210306:023654.800 End of zbx_load_modules():SUCCEED
 24012:20210306:023654.800 In init_collector_data()
 24012:20210306:023654.800 In zbx_dshm_create() size:0
 24012:20210306:023654.800 End of zbx_dshm_create():SUCCEED shmid:-1
 24012:20210306:023654.800 End of init_collector_data()

zabbix_agentd (daemon) (Zabbix) 5.2.5
zabbix_server version : (Zabbix) 5.2.2

Problem persists on several agents when same version is used.

**Comment by eth001** [comment]
** Update : I was able to repeat the problem on Ubuntu 20.04 as well **
I get : 
176397:20210306:025323.715 cannot find "zbx_module_history_write_cbs()" function in module "/etc/zabbix/m
ods/zabbix_module_docker.so": /etc/zabbix/mods/zabbix_module_docker.so: undefined symbol: zbx_module_hist
ory_write_cbs

**Comment by i-ky** [comment]
> 176397:20210306:025323.715 cannot find "zbx_module_history_write_cbs()" function in module "/etc/zabbix/m
ods/zabbix_module_docker.so": /etc/zabbix/mods/zabbix_module_docker.so: undefined symbol: zbx_module_hist
ory_write_cbs

This is not an actual error, it's just a diagnostic message that Zabbix couldn't find _optional_ module API function. You can safely ignore this message. It is not related to your problem:

> I cannot get docker info from my zabbix agent.

**Comment by eth001** [comment]
I am trying to ignore it, but all my systems are getting same error, I have solved all other problems except this one.
![image](https://user-images.githubusercontent.com/57868580/110201780-fb75b200-7e75-11eb-8078-77b1113610f7.png)

**Comment by jangaraj** [comment]
That `Problem` is not coming from the template from this project, so I'm closing this issue. 

It looks like you are using official Zabbix Docker template, so you need also their Docker metrics collection (check official Zabbix doc how to do that). You are mixing this projects with official Zabbix Docker monitoring.
