### ISSUE TITLE
Metric name with com.docker.swarm.service.name var

### ISSUE THREAD

**Issue by crazyxoma** [monitoringartist/zabbix-docker-monitoring#164]
Hello! I installed your agent near docker swarm... Thats ok. But after restart - zabbix starts to collect new metrics as after docker restart creats new containers with suffix like
swarm_app-nginx.1.u0rukjtcr1fav97gvijuvi0g9 - first time
swarm_app-nginx.1.prqu3gezdduck0u16axssdh8d - next time 

And we have different metrics:
Example: CPU system time swarm_app-nginx.1.u0rukjtcr1fav97gvijuvi0g9

Is it possible to use com.docker.swarm.service.name var for mocros like
{#FCONTAINERID}, {#SCONTAINERID}, {#HCONTAINERID} and for example {#SWARMCONTAINERID} 
?

**Comment by jangaraj** [comment]
In theory it's possible to code it. But then users of other orchestrations (Kubernetes, OpenShift, Nomad, ...) will be asking for the same and it won't be Docker monitoring, but orchestration monitoring (with additional API communication for each orchestration type). I see this project as an Docker container monitoring, not orchestration monitoring. 

From the architecture point of view I see dedicated orchestration monitoring will be better. And it will be using this project for underlying Docker container monitoring. So actually, I don't see this repo as an right place, where it should be implemented.
