### ISSUE TITLE
Cannot find the [networks][eth0][rx_bytes] item in the received JSON object

### ISSUE THREAD

**Issue by Jonybat** [monitoringartist/zabbix-docker-monitoring#166]
Hi

First of all, thanks for this great module :+1: 

Had this working without issues in multiple Zabbix 4.4 hosts (with self compiled module). Upgraded today to 5.0 and uploaded your pre compiled modules for the same version.

Everything seems to be working fine, except for the docker.stats items.
An item example: `docker.stats[activemq,networks,eth0,rx_bytes]`, used to work, but now returns: `ZBX_NOTSUPPORTED: Cannot find the [networks][eth0][rx_bytes] item in the received JSON object`.

Setting Zabbix log level to 4, can see the valid JSON in the response. In fact, removing the `rx_bytes` from the item, returns valid JSON, where `rx_bytes` is present:
```
$ zabbix_get -s <IP_redacted> -k docker.stats[activemq,networks,eth0]
{"rx_bytes": 585937462, "rx_packets": 3710571, "rx_errors": 0, "rx_dropped": 0, "tx_bytes": 454716472, "tx_packets": 3675137, "tx_errors": 0, "tx_dropped": 0}
$ zabbix_get -s <IP_redacted> -k docker.stats[activemq,networks,eth0,rx_bytes]
ZBX_NOTSUPPORTED: Cannot find the [networks][eth0][rx_bytes] item in the received JSON object
```

I have a workaround for now, by creating an item as described above, and then dependent items for each of the JSON selectors, using Zabbix's JSONPath preprocessor, but would be nice to have this working again, due to data volume.

Cheers

**Comment by i-ky** [comment]
@Jonybat do you recall which version of the module you were using with 4.4? Crucially, was it before #152 or after? This is the most likely reason of the change in behaviour. If you still have the module binary you can check with `ldd` if `libjansson` is linked.

**Comment by Jonybat** [comment]
Hey. I dont, but it was built against Zabix 4.4.7, so it was between March/April 2020, meaning it was before that libjansson change.

Surely enough:
```
ldd zabbix_module_docker-4.4.7.so 
	linux-vdso.so.1 (0x00007ffcdb796000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f18f2a5e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f18f2c5f000)
```

I noticed this new dependency when deploying the new module, but didnt even give it a second thought.

**Comment by i-ky** [comment]
For some reason current code assumes that the value user wants to get with a `docker.stats[<container>,<param1>,<param2>,<param3>]` key must be a JSON string: https://github.com/monitoringartist/zabbix-docker-monitoring/blob/efcfe89c333c79c481a53f7e3b3dc43f991997d0/src/modules/zabbix_module_docker/zabbix_module_docker.c#L2021 In your case it is a number, this results in "Cannot find ..." error.

I have to double check the code before #152 to understand why this "must be a string" assumption was made. Apparently, I overlooked something.

**Comment by i-ky** [comment]
@Jonybat, please give #170 a test.
