### ISSUE TITLE
missing documentation on how to install zabbix_module_docker.so

### ISSUE THREAD

**Issue by another-random-username-0** [monitoringartist/zabbix-docker-monitoring#176]
Hi,
I ve read and re-read the github and searched with google but i couldnt find how to install zabbix_module_docker.so ? 
Am i supposed to copy it to the default install folder in linux /usr/share/zabbix/modules/mymodule and wait? 
THank you

**Comment by i-ky** [comment]
@aurelpere, location (and also name) of the .so file does not matter as long as you [configure Zabbix agent/proxy/server](https://www.zabbix.com/documentation/current/en/manual/config/items/loadablemodules#configuration-parameters) accordingly and Zabbx can access the given path.

**Comment by jangaraj** [comment]
Yes, info how to use .so file is not covered in the doc. Instead there is a link to official Zabbix `Loadable modules` doc (linked also by @i-ky in the previous comment). It is a part of installation section: https://github.com/monitoringartist/zabbix-docker-monitoring#installation
