### ISSUE TITLE
Use container name instead of id in item keys?

### ISSUE THREAD

**Issue by franzk** [monitoringartist/Zabbix-Docker-Monitoring#20]
Hi Jan,

I just realised my Zabbix monitoring setup has a certain 'downside', which I try to describe it in short:

Most items use the the full container ID to identify a container. If I recreate a container, this ID will change of course. Zabbix will show up the new items once it has discovered the "new" container, and the old items referring to the former container id will receive no data anymore. I have a graph instance as part of a Zabbix screen, and upon container recreation, it still traces the old container and gets deleted after the "keep" period defined in the discovery rule...

What do you think about putting the container name into all item keys instead of the id? Docker enforces the container name to be unique. That way, item, trigger and graph instances would survive container recreations. 

I have some doubts that taking the sole name might not be desirable for scaled containers (but they would cause dozens of trigger events as well...), what do you think? Do you have the same 'problem' or is it bound to my specific use case? :-)

Cheers,
Franz

**Comment by jangaraj** [comment]
I've chosen full container ID, because performance. Module can read pseudo files directly, no translation from name to container ID is required now. This translation requires at least one docker API query. So I'll expect more than 50% performance degradation, when I allow container name instead of container ID.
\+ new container is technically different instance, but yes it can be the same container logically
\+ container name is not mandatory

Good news for you: you can use also container name for some keys - they use only pure docker API queries, e.g *docker.inspect* and *docker.stat*:
```
[root@docker]# zabbix_get -s 127.0.0.1 -k docker.stats[6fac1f4cca58da8dc17ae8d0091922888c247f90fa6be806dffabd74111f7402,cpu_stats,cpu_usage,total_usage]
13334651149
[root@docker]# zabbix_get -s 127.0.0.1 -k docker.stats[zabbix-db,cpu_stats,cpu_usage,total_usage]
13345474922
[root@zenossmaster zabbix_module_docker]# zabbix_get -s 127.0.0.1 -k docker.inspect[6fac1f4cca58da8dc17ae8d0091922888c247f90fa6be806dffabd74111f7402,State,StartedAt]
2015-07-16T22:38:55.05691989Z
[root@docker]# zabbix_get -s 127.0.0.1 -k docker.inspect[zabbix-db,State,StartedAt]
2015-07-16T22:38:55.05691989Z
```
You will need to create your own discovery (HCONTAINERID is container name) and item prototypes with *docker.stats*. Performance of docker.stats is not the best, because docker stat stream must be parsed. If you don't have hundreds of running containers, then it can be fine.

Please try this one and let me know how is it going. If it's terrible solution, then I can consider to implement also container names :-)

**Comment by jangaraj** [comment]
Please clone and test mesos branch (7cc4c2524267ae567ecdf69823ce0882c9dabbf4). This branch allows you to use also container name instead of id. Performance is the same, so it will added to master branch after verification:
```
[root@docker]# ./zabbix-agent-stress-test.py -s 127.0.0.1 -k " docker.cpu[6fac1f4cca58da8dc17ae8d0091922888c247f90fa6be806dffabd74111f7402,system]" -t 20
Warning: you are starting more threads, than your system has available CPU cores (4)!
Starting 20 threads, host: 127.0.0.1:10050, key:  docker.cpu[6fac1f4cca58da8dc17ae8d0091922888c247f90fa6be806dffabd74111f7402,system]
Success: 3064   Errors: 0       Avg rate: 5108.42 qps   Execution time: 1.00 sec
Success: 5747   Errors: 0       Avg rate: 3939.85 qps   Execution time: 2.00 sec
Success: 8421   Errors: 0       Avg rate: 4372.12 qps   Execution time: 3.01 sec
Success: 10955  Errors: 0       Avg rate: 3042.30 qps   Execution time: 4.01 sec
Success: 13197  Errors: 0       Avg rate: 2533.29 qps   Execution time: 5.02 sec
Success: 15892  Errors: 0       Avg rate: 3986.48 qps   Execution time: 6.02 sec
Success: 18544  Errors: 0       Avg rate: 5827.35 qps   Execution time: 7.02 sec
Success: 21145  Errors: 0       Avg rate: 4016.35 qps   Execution time: 8.03 sec
Success: 23733  Errors: 0       Avg rate: 3759.72 qps   Execution time: 9.04 sec
Success: 26338  Errors: 0       Avg rate: 4374.02 qps   Execution time: 10.04 sec
Success: 28981  Errors: 0       Avg rate: 6035.50 qps   Execution time: 11.04 sec
Success: 31579  Errors: 0       Avg rate: 4489.76 qps   Execution time: 12.05 sec
Success: 34217  Errors: 0       Avg rate: 2061.12 qps   Execution time: 13.05 sec
Success: 36881  Errors: 0       Avg rate: 4996.64 qps   Execution time: 14.05 sec
Success: 39407  Errors: 0       Avg rate: 4253.39 qps   Execution time: 15.06 sec
Success: 42022  Errors: 0       Avg rate: 2637.70 qps   Execution time: 16.06 sec
Success: 44658  Errors: 0       Avg rate: 4992.70 qps   Execution time: 17.06 sec
Success: 47297  Errors: 0       Avg rate: 4168.94 qps   Execution time: 18.07 sec
Success: 49918  Errors: 0       Avg rate: 3902.22 qps   Execution time: 19.07 sec
Success: 52519  Errors: 0       Avg rate: 2367.01 qps   Execution time: 20.08 sec
^C
Success: 53288  Errors: 0       Avg rate: 4388.24 qps   Execution time: 20.37 sec
Avg rate based on total execution time and success connections: 2616.25 qps
[root@docker]# ./zabbix-agent-stress-test.py -s 127.0.0.1 -k " docker.cpu[zabbix-db,system]" -t 20
Warning: you are starting more threads, than your system has available CPU cores (4)!
Starting 20 threads, host: 127.0.0.1:10050, key:  docker.cpu[zabbix-db,system]
Success: 2915   Errors: 0       Avg rate: 2115.24 qps   Execution time: 1.00 sec
Success: 5638   Errors: 0       Avg rate: 2365.15 qps   Execution time: 2.00 sec
Success: 8355   Errors: 0       Avg rate: 5027.16 qps   Execution time: 3.00 sec
Success: 11007  Errors: 0       Avg rate: 3669.21 qps   Execution time: 4.01 sec
Success: 13613  Errors: 0       Avg rate: 2652.02 qps   Execution time: 5.01 sec
Success: 16288  Errors: 0       Avg rate: 3266.96 qps   Execution time: 6.01 sec
Success: 18932  Errors: 0       Avg rate: 2812.09 qps   Execution time: 7.01 sec
Success: 21511  Errors: 0       Avg rate: 5746.14 qps   Execution time: 8.02 sec
Success: 24124  Errors: 0       Avg rate: 3018.28 qps   Execution time: 9.02 sec
Success: 26672  Errors: 0       Avg rate: 4007.39 qps   Execution time: 10.02 sec
Success: 29267  Errors: 0       Avg rate: 3852.82 qps   Execution time: 11.02 sec
Success: 31848  Errors: 0       Avg rate: 3019.30 qps   Execution time: 12.03 sec
Success: 34514  Errors: 0       Avg rate: 5278.36 qps   Execution time: 13.04 sec
Success: 37195  Errors: 0       Avg rate: 5567.46 qps   Execution time: 14.04 sec
Success: 39748  Errors: 0       Avg rate: 5984.71 qps   Execution time: 15.05 sec
Success: 42419  Errors: 0       Avg rate: 3258.78 qps   Execution time: 16.05 sec
Success: 45065  Errors: 0       Avg rate: 4309.21 qps   Execution time: 17.06 sec
Success: 47750  Errors: 0       Avg rate: 2517.98 qps   Execution time: 18.06 sec
Success: 50398  Errors: 0       Avg rate: 7349.19 qps   Execution time: 19.07 sec
Success: 52919  Errors: 0       Avg rate: 8242.04 qps   Execution time: 20.07 sec
^C
Success: 53931  Errors: 0       Avg rate: 3233.00 qps   Execution time: 20.47 sec
Avg rate based on total execution time and success connections: 2635.34 qps
```

**Comment by chernogorsky** [comment]
And right now this only by manual added items ? AD doesnt work ?

**Comment by jangaraj** [comment]
Only code of module was updated, not template (for now). You will need to
update your autodiscovery rule manually.

*Jan Garaj*
Email/IM: jan.garaj@gmail.com
   Mobile: *+44 79 234 69004* (*+421 949 113 911*)
      Web: http://www.jangaraj.com / http://monitoringartist.com
LinkedIn: http://www.linkedin.com/in/jangaraj

**Comment by jangaraj** [comment]
Feature is available in master branch. Also templates have been updated - default container id is container name now.
