### ISSUE TITLE
ZBX_NOTSUPPORTED: Cannot open Docker container cpuacct.stat/memory.stat file on Ubuntu:14.04

### ISSUE THREAD

**Issue by hanxiaole** [monitoringartist/Zabbix-Docker-Monitoring#21]
When I load the latest zabbix_module_docker.so file into zabbix_agent 2.4.6-1 to monitor memerory/cpu  of  containers on Ubutu:14.04 bare machine, but zabbix_get receive "ZBX_NOTSUPPORTED: Cannot open Docker container cpuacct.stat/memory.stat file" message to me.
It's ok to get the docker.discovery infos.

docker version: 1.6.2
server: ubuntu:14.04 
zabbix: 2.4.6-1

**Comment by jangaraj** [comment]
Enable debug in zabbix agent config file and restart agent. Then pls provide me zabbbix agent logs after restart. There will be more information - e.g. detected cgroup directory, etc.

**Comment by hanxiaole** [comment]
The problem is that  using {#HCONTAINERID} in any mem/cpu stats cannot found the statitics location , but {#FCONTANIERID} work properly. 

here is the zabbix agent output:
===================================================================
  2416:20150902:170305.685 Metric source file: /sys/fs/cgroup/cpuacct/docker/ubuntu/cpuacct.stat
  2416:20150902:170305.685 Cannot open Docker container metric file: '/sys/fs/cgroup/cpuacct/docker/ubuntu/cpuacct.stat'
====================================================================


below is the output of  statment i executed.
====================================================================
[root@centos6 /]# zabbix_get  -s 10.10.77.123 -k docker.discovery
{"data":[{"{#FCONTAINERID}":"928e19d3581ed6a68147f0422e974a3f3cd602197a59cffca02b45f6c74ac8b9","{#HCONTAINERID}":"ubuntu"}]}
[root@centos6 /]# zabbix_get  -s 10.10.77.123 -k docker.cpu[ubuntu,system]
ZBX_NOTSUPPORTED: Cannot open Docker container cpuacct.stat file
[root@centos6 /]# zabbix_get  -s 10.10.77.123 -k docker.cpu[928e19d3581ed6a68147f0422e974a3f3cd602197a59cffca02b45f6c74ac8b9,system]
0
====================================================================

**Comment by jangaraj** [comment]
I need start logs, example (https://github.com/monitoringartist/Zabbix-Docker-Monitoring/issues/11):
```
20403:20150630:163637.302 Starting Zabbix Agent [*******]. Zabbix 2.4.5 (revision 53282).
 20403:20150630:163637.302 using configuration file: /etc/zabbix/zabbix_agentd.conf
 20403:20150630:163637.302 In load_modules()
 20403:20150630:163637.302 loading module "/usr/lib/samepage/zabbix/modules/zabbix_module_docker.so"
 20403:20150630:163637.303 In zbx_module_api_version()
 20403:20150630:163637.303 In zbx_module_init()
 20403:20150630:163637.303 zabbix_module_docker v0.3.0, compilation time: Jun 18 2015 06:08:55
 20403:20150630:163637.303 In zbx_docker_dir_detect()
 20403:20150630:163637.303 Detected docker stat directory: /sys/fs/cgroup/
 20403:20150630:163637.303 Cannot detect used docker driver
 20403:20150630:163637.303 In zbx_docker_perm()
 20403:20150630:163637.303 zabbix agent user has docker perm
 20403:20150630:163637.303 In zbx_module_docker_socket_query()
```

**Comment by hanxiaole** [comment]
here is the output and it  looks  fine.


 2904:20150902:171850.779 Starting Zabbix Agent [docker-master]. Zabbix 2.4.6 (revision 54796).
  2904:20150902:171850.779 using configuration file: /etc/zabbix/zabbix_agentd.conf
  2904:20150902:171850.779 In load_modules()
  2904:20150902:171850.779 loading module "/etc/zabbix/zabbix_module_docker.so"
  2904:20150902:171850.779 In zbx_module_api_version()
  2904:20150902:171850.779 In zbx_module_init()
  2904:20150902:171850.779 zabbix_module_docker v0.5.0, compilation time: Aug 29 2015 12:23:58
  2904:20150902:171850.779 In zbx_docker_dir_detect()
  2904:20150902:171850.779 Detected docker stat directory: /sys/fs/cgroup/
  2904:20150902:171850.779 Detected used docker driver dir: docker/
  2904:20150902:171850.779 In zbx_module_docker_socket_query()
  2904:20150902:171850.779 Docker's socket query: GET /_ping HTTP/1.0
  2904:20150902:171850.780 Docker's socket response: OK
  2904:20150902:171850.780 Docker's socket works - extended docker metrics are available
  2904:20150902:171850.780 In zbx_module_item_timeout()
  2904:20150902:171850.780 In register_module()
  2904:20150902:171850.780 End of register_module():SUCCEED
  2904:20150902:171850.780 In zbx_module_item_list()
  2904:20150902:171850.780 loaded modules: zabbix_module_docker.so
  2904:20150902:171850.780 End of load_modules():SUCCEED
  2904:20150902:171850.780 In init_collector_data()
  2904:20150902:171850.780 End of init_collector_data()
  2904:20150902:171850.780 agent #0 started [main process]
  2908:20150902:171850.781 agent #4 started [listener #3]
  2908:20150902:171850.781 listener #3 [waiting for connection]
  2909:20150902:171850.781 agent #5 started [active checks #1]
  2909:20150902:171850.781 In init_active_metrics()
  2909:20150902:171850.781 buffer: first allocation for 100 elements
  2909:20150902:171850.781 In send_buffer() host:'10.10.77.126' port:10051 values:0/100
  2909:20150902:171850.781 End of send_buffer():SUCCEED
  2909:20150902:171850.781 active checks #1 [getting list of active checks]
  2909:20150902:171850.781 In refresh_active_checks() host:'10.10.77.126' port:10051
  2907:20150902:171850.782 agent #3 started [listener #2]
  2907:20150902:171850.782 listener #2 [waiting for connection]
  2906:20150902:171850.782 agent #2 started [listener #1]
  2906:20150902:171850.782 listener #1 [waiting for connection]
  2909:20150902:171850.782 sending [{"request":"active checks","host":"docker-master"}]
  2909:20150902:171850.782 before read
  2905:20150902:171850.782 agent #1 started [collector]
  2905:20150902:171850.782 In init_cpu_collector()
  2905:20150902:171850.782 End of init_cpu_collector():SUCCEED
  2905:20150902:171850.782 collector [processing data]
  2905:20150902:171850.782 In update_cpustats()
  2905:20150902:171850.782 End of update_cpustats()
  2905:20150902:171850.783 collector [idle 1 sec]
  2909:20150902:171850.829 got [{"response":"failed","info":"host [docker-master] not found"}]
  2909:20150902:171850.829 In parse_list_of_checks()
  2909:20150902:171850.829 In disable_all_metrics()
  2909:20150902:171850.829 no active checks on server [10.10.77.126:10051]: host [docker-master] not found
  2909:20150902:171850.829 End of refresh_active_checks():SUCCEED
  2909:20150902:171850.829 active checks #1 [processing active checks]
  2909:20150902:171850.829 In process_active_checks() server:'10.10.77.126' port:10051)
  2909:20150902:171850.829 End of process_active_checks()
  2909:20150902:171850.829 In get_min_nextcheck()
  2909:20150902:171850.829 active checks #1 [idle 1 sec]
  2905:20150902:171851.783 collector [processing data]
  2905:20150902:171851.783 In update_cpustats()
  2905:20150902:171851.783 End of update_cpustats()
  2905:20150902:171851.783 collector [idle 1 sec]
  2909:20150902:171851.829 In send_buffer() host:'10.10.77.126' port:10051 values:0/100
  2909:20150902:171851.830 End of send_buffer():SUCCEED
  2909:20150902:171851.830 active checks #1 [idle 1 sec]
  2905:20150902:171852.783 collector [processing data]
  2905:20150902:171852.783 In update_cpustats()
  2905:20150902:171852.783 End of update_cpustats()
  2905:20150902:171852.783 collector [idle 1 sec]
  2909:20150902:171852.830 In send_buffer() host:'10.10.77.126' port:10051 values:0/100
  2909:20150902:171852.830 End of send_buffer():SUCCEED
  2909:20150902:171852.830 active checks #1 [idle 1 sec]
  2905:20150902:171853.783 collector [processing data]

**Comment by jangaraj** [comment]
Pls try also:
```
zabbix_get  -s 10.10.77.123 -k docker.cpu[\ubuntu,system]
```
Human names must have prefix '\' (this feature was merged recently - also template was updated - maybe this is your problem).

**Comment by hanxiaole** [comment]
thk for suggestion. it's my fault to ignore the slach -- '/'.
i will close the issue.

**Comment by jangaraj** [comment]
No problem, ywc.
