### ISSUE TITLE
Bytes counter with docker.xnet items

### ISSUE THREAD

**Issue by eimamagi** [monitoringartist/Zabbix-Docker-Monitoring#26]
Hello, 

docker.xnet uses "netstat -i" which does not provide bytes counter. Bytes could be fetched by using something like "ip -s link". Do you plan to add support for bytes counter? 

Another question - since docker.xnet invokes ip exec for each item do you think it is better to use stats for network statistics?

Thanks in advance,
emir

**Comment by jangaraj** [comment]
If you really need bytes counter now, then you can use:
```
docker.stats[cid,network,rx_bytes], 
```
docker.xnet is not the best implementation (that's the reason of x - experimental, extreme inefficient :-) )
I'm open for new ideas for implementation of docker.(x)net. Please let me know, what do you mean with "use stats for network statistics".

Reference:
https://docs.docker.com/articles/runmetrics/

Thank you.

**Comment by eimamagi** [comment]
Hi,

By "stats for network statistics" I meant docker.stats item. Ok, thank you for clarifying that is the way to go for network stats.

I was checking xnet only because I am on docker < 1.5. I went through the reference link (very informative :)) and namespaces was their recommendation.

So in conclusion - definitely we should upgrade and go for docker.stats if we want network?

Thanks
emir

**Comment by jangaraj** [comment]
You can create also own user parameter, which will use net namespaces created by Zabbix agent (but you need collect also module metrics). Concept:
```
# $1 should be $CID - container id
UserParameter=docker.net_myimplementation[*],ip netns exec $1 ip -s link | <parsing commands, which will provide required metric value>
```
And you can add new LLD, which will create zabbix items with your key automatically.

To be honest _docker.stats_ is still not the best option, because is waiting for docker stats stream. It can be serious performance problem for high density (1000 containers every second) monitoring.

**Comment by eimamagi** [comment]
Since we do have some high density hosts I was thinking of one big script that will report passive results. I would use docker.discovery to create passive zabbix LLD items for network statistics per container. That way I wouldn't need to invoke netns exec for each item as we'll have at least 4 per container.

**Comment by jangaraj** [comment]
http://monitoringartist.github.io/zabbix-searcher/#docker check szimon implementation (at least for inspiration) - scripted python solution, which is using sender

**Comment by jangaraj** [comment]
I'm closing issue, because you have ideas how to solve your problem and I still know, that current implementation of net metrics is not the best.
