### ISSUE TITLE
Discovery names and linked containers confusion

### ISSUE THREAD

**Issue by xeor** [monitoringartist/zabbix-docker-monitoring#32]
I noticed some of my containers was named like `d1_splunk_1/d1_front_1`, which is a name in the list of "Names" in the Docker API. The example here is what the `d1_front_1` container ends up being named when using the default `docker.discovery`. I still have a container named `d1_splunk_1`, but not another one of `d1_front_1`. https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#list-containers says it should be a list, and that list of containers containers linked containers as well.
Basically, it the same list as `docker ps -a --no-trunc`. I see no guaranty by the API that the name of the container should come first, and it doesnt look like it does either.
So https://github.com/monitoringartist/Zabbix-Docker-Monitoring/blob/master/src/modules/zabbix_module_docker/zabbix_module_docker.c#L1570 is wrong :)

Turning on the truncated output in the API gives the short-name, but also gives us the shortened ID's, which wont work with getting CPU stats and so on.

Another way I found was looking for the entry in the `Names` array that contains 1 `/`.

I ended up writing a little python `docker.discover2` in the meantime, to get the correct name. But this might be something to do in the module itself? What do you think?
If the length of the array is not `1` after the `/` check, you could fallback on grabbing the first one. Even tho I don't think that will happen.. :)

**Comment by jangaraj** [comment]
Could you attach your python `docker.discover2` implementation please?

**Comment by xeor** [comment]
Sorry.. Here you go :)

    #!/usr/bin/env python
    
    import json
    
    # pip install docker-py
    from docker import Client
    cli = Client(base_url='unix://var/run/docker.sock')
    
    data = {'data': []}
    
    for c in cli.containers():
      cdata = {}
      cdata['{#FCONTAINERID}'] = c['Id']
    
      # If we use trunc, we also loose the full Id. They are taling about changing the API
      # to truncate linked containers as default. Till then, do this.
      name = filter(lambda x: x.count('/') == 1, c['Names'])
      if len(name) == 1:
        cdata['{#HCONTAINERID}'] = name[0].strip('/')
      else:
        cdata['{#HCONTAINERID}'] = c['Names'][0].strip('/')  # fallback, dont know if this can happen... :)
    
      data['data'].append(cdata)
    
    print json.dumps(data)

**Comment by jangaraj** [comment]
Yes, it needs better implementation.
