### ISSUE TITLE
Zabbix wont start correctly

### ISSUE THREAD

**Issue by xeor** [monitoringartist/Zabbix-Docker-Monitoring#33]
There is a problem happening when zabbix is trying to start up after a reboot. A restart of zabbix after boot manually fixes solves the problem. So this is only happening on boot.

I sat the zabbix-agent debug log to 4, and this is what was in the log;

* Woulnt start, had zabbix-docker-monitoring enabled
```
1381:20151209:225333.348 Starting Zabbix Agent [d3]. Zabbix 2.4.7 (revision 56694).
1381:20151209:225333.348 using configuration file: /etc/zabbix/zabbix_agentd.conf
1381:20151209:225333.348 In load_modules()
1381:20151209:225333.348 loading module "/usr/local/lib/zabbix/agent//zabbix_module_docker.so"
1381:20151209:225333.348 In zbx_module_api_version()
1381:20151209:225333.348 In zbx_module_init()
1381:20151209:225333.348 zabbix_module_docker v0.5.0, compilation time: Dec  2 2015 22:39:38
1381:20151209:225333.348 In zbx_docker_dir_detect()
1381:20151209:225333.349 Detected docker stat directory: /sys/fs/cgroup/
1381:20151209:225333.349 Cannot detect used docker driver
1381:20151209:225333.349 In zbx_module_docker_socket_query()
1381:20151209:225333.349 Docker's socket query: GET /_ping HTTP/1.0
.... hangs here ....
```

* Disabling the module, this is what happened

```
1384:20151209:225916.324 Starting Zabbix Agent [d3]. Zabbix 2.4.7 (revision 56694).
1384:20151209:225916.324 using configuration file: /etc/zabbix/zabbix_agentd.conf
1384:20151209:225916.324 In load_modules()
1384:20151209:225916.324 End of load_modules():SUCCEED
1384:20151209:225916.324 In init_collector_data()
1384:20151209:225916.324 End of init_collector_data()
1384:20151209:225916.324 agent #0 started [main process]
1388:20151209:225916.325 agent #3 started [listener #2]
1388:20151209:225916.325 listener #2 [waiting for connection]
1390:20151209:225916.325 agent #5 started [active checks #1]
1389:20151209:225916.325 agent #4 started [listener #3]
1390:20151209:225916.326 In init_active_metrics()
1387:20151209:225916.326 agent #2 started [listener #1]
1389:20151209:225916.326 listener #3 [waiting for connection]
1390:20151209:225916.326 buffer: first allocation for 100 elements
.... full start, a lot of output ....
```

The only zabbix proccess that is able to start when the module is enabled is `/usr/sbin/zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf`. Running `strace -p ...` on it only displays `read(4,`.

When the module is not enabled, these proccesses are able to start;
```
/usr/sbin/zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf
/usr/sbin/zabbix_agentd: collector [idle 1 sec]
/usr/sbin/zabbix_agentd: listener #1 [waiting for connection]
/usr/sbin/zabbix_agentd: listener #2 [waiting for connection]
/usr/sbin/zabbix_agentd: listener #3 [waiting for connection]
/usr/sbin/zabbix_agentd: active checks #1 [idle 1 sec]
```

It's almost like the module doesn't report back to zabbix that it is done loading and zabbix can continue.

If I do `systemctl restart zabbix` when the system is up, zabbix is able to start, even with the plugin loaded.

Env:
* Centos 7
* zabbix-agent-2.4.7-1.el7.x86_64
* selinux states; tried both enforcing and permissive

**Comment by jangaraj** [comment]
When you are in the state:
```
1381:20151209:225333.349 Docker's socket query: GET /_ping HTTP/1.0
.... hangs here ....
```
test it in cmd:
```
 echo -e "GET /_ping HTTP/1.0\r\n" | nc -U /var/run/docker.sock
```
You should to see OK response from the docker:
```
[root@host ~]#  echo -e "GET /_ping HTTP/1.0\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Server: Docker/1.8.2 (linux)
Date: Wed, 09 Dec 2015 22:32:00 GMT
Content-Length: 2
Content-Type: text/plain; charset=utf-8

OK
```
Apparently module is waiting for `ping` docker response.
Which docker version do you have and how did you install it?

**Comment by xeor** [comment]
`echo -e "GET /_ping HTTP/1.0\r\n" | nc -U /var/run/docker.sock` returns OK without delay.
I am running `Docker version 1.9.1, build a34a1d5` from rpm packages @ `https://yum.dockerproject.org/repo/main/centos/7`.

Maybe it starts up before docker, but doesn't recheck after docker is done starting up.

.......

Found a solution, pull-request coming up :)

**Comment by jangaraj** [comment]
I expect timeout for Docker ping request -> advanced Docker metric won't be available for a moment (not supported state). When next request will pass Docker ping test, then everything will be back to normal - also advanced metrics will be available. Some timeout should be implemented for Docker socket query.
