### ISSUE TITLE
Cannot open Docker container metric file: '/cgroup/cpuacct/docker/cid/cpuacct.stat'

### ISSUE THREAD

**Issue by maneeshmp** [monitoringartist/Zabbix-Docker-Monitoring#36]
In Amazon AMI linux, cpuacct.stat file exist under '/cgroup/cpuacct/docker/' directory. So I get the below error.

14939:20160107:084044.381 Cannot open Docker container metric file: '/cgroup/cpuacct/docker/cid/cpuacct.stat'

**Comment by jangaraj** [comment]
Please provide more details:
- Linux/Docker/kernel version
- listing of /cgroup/cpuacct/docker/ and /cgroup/cpuacct/docker/cid

Is container cid up and running?

**Comment by maneeshmp** [comment]
Here you go..
$uname -a
Linux ip-10-37-120-237 4.1.10-17.31.amzn1.x86_64 #1 SMP Sat Oct 24 01:31:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ docker --version
Docker version 1.7.1, build 786b29d/1.7.1
$ pwd
/cgroup/cpuacct/docker
$ls 
 4d4a2ceesdfasdfsdfsdfasdfsdaf2342342342270df90eb13141963d0edcb50da3634cf9bc   csdfsdfsdfdfsdaf8afcbc18eaf510593aacf7b6269d0aa6397adcdb1af5b9  cgroup.clone_children  cgroup.procs  cpuacct.stat  cpuacct.usage  cpuacct.usage_percpu  notify_on_release  tasks

cd /cgroup/cpuacct/docker/cid
-bash: cd: /cgroup/cpuacct/docker/cid: No such file or directory

**Comment by jangaraj** [comment]
Please provide full zabbix agent log + how did you configure Docker template/host in Zabbix UI.

**Comment by maneeshmp** [comment]
I have used the attached zabbix agent source. 
1. Extracted to /etc/zabbix.
2. Executed /etc/zabbix/configure --enable-agent && make && make install
3. Downloaded zabbix_module_docker.c & Makefile and placed under /etc/zabbix/src/modules/docker   [ docker directory is created by me]
4. Executed the command -> make
5.. make command created the file zabbix_module_docker.so
6. in /etc/zabbix/zabbix_agentd.conf, updated the paths
    LoadModulePath=/etc/zabbix/src/modules/docker
    LoadModule=zabbix_module_docker.so
7.Used zbx_export_templates.xml (changed the extension to .txt for uploading)

Logs:

 ........................
 zabbix_agentd [14861]: Error on thread waiting.
 14861:20160107:083611.554 Zabbix Agent stopped. Zabbix 2.2.10 (revision 54806).
 14932:20160107:083611.660 Starting Zabbix Agent [docker]. Zabbix 2.2.10 (revision 54806).
 14932:20160107:083611.660 using configuration file: /etc/zabbix/zabbix_agentd.conf
 14932:20160107:083611.661 loaded modules: zabbix_module_docker.so
 14940:20160107:083611.661 agent #6 started [active checks #1]
 14938:20160107:083611.662 agent #4 started [listener #4]
 14936:20160107:083611.662 agent #2 started [listener #2]
 14934:20160107:083611.662 agent #0 started [collector]
 14935:20160107:083611.662 agent #1 started [listener #1]
 14939:20160107:083611.662 agent #5 started [listener #5]
 14937:20160107:083611.662 agent #3 started [listener #3]
 .......................
 .......................
 14939:20160107:083744.021 Cannot open Docker container metric file: '/cgroup/cpuacct/docker/cid/cpuacct.stat'
 14940:20160107:084011.946 active check "agent.hostgroup" is not supported
 14940:20160107:084011.948 active check "agent.template" is not supported
 14940:20160107:084011.948 active check "agent.visible.name" is not supported
 14940:20160107:084011.949 active check "vfs.dev.write[vda,sps,avg1]" is not supported
 14939:20160107:084044.381 Cannot open Docker container metric file: '/cgroup/cpuacct/docker/cid/cpuacct.stat'
 .......................
 .......................


[zbx_export_templates.txt](https://github.com/monitoringartist/Zabbix-Docker-Monitoring/files/82075/zbx_export_templates.txt)
 
[zabbix-2.2.10.zip](https://github.com/monitoringartist/Zabbix-Docker-Monitoring/files/82060/zabbix-2.2.10.zip)

**Comment by jangaraj** [comment]
Why are you using:
``` 
<key>docker.cpu[cid,system]</key>
```

Zabbix Docker module explains `cid`:
> Note: cid - container ID, two options are available:
>
>    -full container ID (fid - 64 character string), e.g. 2599a1d88f75ea2de7283cbf469ea00f0e5d42aaace95f90ffff615c16e8fade (human) name or short
> -container ID - prefix "/" must be used, e.g. /zabbix-server or /2599a1d88f75

For example: you have to use:
```
docker.cpu[2599a1d88f75ea2de7283cbf469ea00f0e5d42aaace95f90ffff615c16e8fade,system]
```

This is not a bug, but configuration problem. Please read Zabbix Docker module, Zabbix documentation. If you have any problem with configuration, please community forum/IRC/...
