### ISSUE TITLE
How to configure agent for mesos

### ISSUE THREAD

**Issue by hamsterksu** [monitoringartist/zabbix-docker-monitoring#39]
Hi

According to doc i should use `docker.discovery[Config,Env,MESOS_TASK_ID=]` for mesos cluster.
seems it works for `docker.up[/{#HCONTAINERID}]` only

but it doesn't work for other items.
**Agent prints error:**
`Cannot find the [Config][Env][MESOS_TASK_ID=] item in the received JSON object (selector - param3 doesn't match any value)`

I use template from your git repo - https://github.com/monitoringartist/zabbix-docker-monitoring/blob/master/template/Zabbix-Template-App-Docker.xml 

What is wrong with my settings?

**Screenshots of Zabbix settigns**
1. discovery - https://www.dropbox.com/s/678o6c1yxywowks/zabbix_template_discovery.png
2. items - https://www.dropbox.com/s/gsk8c5yerh87jt7/zabbix_template_items.png

Thanks,

**Comment by jangaraj** [comment]
Is environment variable MESOS_TASK_ID available in you environment?

Jan Garaj

Email/IM: jan.garaj@gmail.com
   Mobile: +44 79 234 69004 (+421 949 113 911)
     Web: http://www.jangaraj.com
LinkedIn: http://www.linkedin.com/in/jangaraj

**Comment by jangaraj** [comment]
No info provided.
