### ISSUE TITLE
Use Docker labels as Zabbix item names

### ISSUE THREAD

**Issue by hrzbrg** [monitoringartist/zabbix-docker-monitoring#40]
Hi,

I am setting up the monitoring for several AWS ECS clusters with around 200 Docker containers and I would love to use your module for it. 

However at the moment I end up with a HCONTAINERID of for example `ecs-PRELIVE-IntelligentSearchService-3-IntelligentSearchService-d2f28fb1a2be81b7e301` which is pretty long.
I understand, that this is the key and it is used for the lookups, but it would be awesome if one could utilize the labels of the container at least for the name of the Zabbix item. This would prevent my very long item names :) 

Is this already possible?

Regards
hrzbrg

**Comment by jangaraj** [comment]
Probably yes. If label is in the output from docker daemon, then yes. (https://github.com/monitoringartist/zabbix-docker-monitoring/blob/master/src/modules/zabbix_module_docker/zabbix_module_docker.c#L1530)

For example you can use environment variable `humanName` as human name `docker.discovery[Config,Env,humanName=]`

**Comment by hrzbrg** [comment]
Okay, I edited the discovery rule as shown in the screenshot below. 
After that the discovery stops working and shows all my containers as down :(

I figured that I should probably leave it as it is, because not all my containers have the variable that I want to use as name. Also on ECS instances there is always an ecs-agent container running.

<img width="511" alt="bildschirmfoto 2016-03-10 um 11 40 05" src="https://cloud.githubusercontent.com/assets/199414/13667048/f2f414b8-e6b4-11e5-9dcf-aea418e35670.png">

Thanks and close.

**Comment by jangaraj** [comment]
YWC. I'll keep it as a feature request: if env variable is not defined use standard container id/human name in docker.discovery

**Comment by jangaraj** [comment]
This feature is alredy implemented:

```
                   } else {
                        zabbix_log(LOG_LEVEL_DEBUG, "Default HCONTAINERID is used, because zbx_module_docker_inspect_exec FAIL: %s", iresult.value);
                        zbx_json_addstring(&j, "{#HCONTAINERID}", names, ZBX_JSON_TYPE_STRING);
                    }
```
