### ISSUE TITLE
Monitoring local disk space of docker host

### ISSUE THREAD

**Issue by drmikecrowe** [monitoringartist/zabbix-docker-monitoring#43]
I'm not able to monitor my disk usage on my docker hosts. Getting:

    item "pr-nodedocker2in:vfs.fs.discovery" became not supported: Unsupported item key.

Is there another solution?

**Comment by jangaraj** [comment]
1.) Project `zabbix-docker-monitoring` doesn't monitor docker hosts.
2.) Probably you are using free public Docker image `monitoringartist/zabbix-agent-xxl-limited`, which is limited and it supports only Docker metrics - paid private Docker image `monitoringartist/zabbix-agent-xxl` supports also Docker hosts metrics.
