### ISSUE TITLE
Error importing template xml

### ISSUE THREAD

**Issue by gianlucamov** [monitoringartist/zabbix-docker-monitoring#44]
Hi,
I have zabbix 2.2.11 on ubuntu 14.04.
I have the following error When trying to import "Zabbix-Template-App-Docker.xml" :

XML file contains fatal error 41:Specification mandate value for attribute data-pjax-transient [ Line: 52 | Column: 40 ]

Any suggestion?
Thank you very much

Gianluca

**Comment by jangaraj** [comment]
Hi Gianluca,

What is on the line 52 of your file Zabbix-Template-App-Docker.xml? Did you download xml (not html) file from the GitHub?

**Comment by gianlucamov** [comment]
Hi jangaraj
shame on me, it downloaded the html with xml extension.
sorry
Gianluca
