### ISSUE TITLE
[Discovery] Group prototypes

### ISSUE THREAD

**Issue by tibo43** [monitoringartist/zabbix-docker-monitoring#47]
Hello,
I need to create group prototype with the hostname of each container agent.
Is it possible to do that by using macros like {#HOST.NAME} ?
I'm working on it for few hours and... nothing for now.
Thanks

**Comment by jangaraj** [comment]
I'm not sure, what do you need, but probably you want to use {#HCONTAINERID}, `docker.discovery` provides macros:
- {#HCONTAINERID} - human container id (name), `zabbix-server`
- {#SCONTAINERID} - short container id, `2599a1d88f75`
- {#FCONTAINERID} - full container id, `2599a1d88f75ea2de7283cbf469ea00f0e5d42aaace95f90ffff615c16e8fade`

**Comment by tibo43** [comment]
Thanks for your answers. I'm sorry for my english.
When I create my host prototype in the discovery rule, I note {#HCONTAINERID} for the Host Name. And in the Groups tab, I would like create one group by hostname of the container agent.

Like that:

![example-1](https://cloud.githubusercontent.com/assets/6716974/15571821/5ef36ee2-233d-11e6-8ea8-7843ce4acd3c.png)

CoreOS_agent is my container agent
 (=> docker run --name=Core-OS -h CoreOS-agent [..] -d monitoringartist/zabbix-agent-xxl-limited:latest)

![example-2](https://cloud.githubusercontent.com/assets/6716974/15571873/bd377e6c-233d-11e6-9831-d189d0ca88c9.png)


![example-3](https://cloud.githubusercontent.com/assets/6716974/15571887/d0c1f6ec-233d-11e6-9429-80287d9fd1b1.png)

Do you understand that I want ?

**Comment by jangaraj** [comment]
Unfortunately there is no {#HOST.NAME} macro available for at the moment. Cold you please upload your Zabbix template and I'll try to check it. It can be a feature request.

**Comment by tibo43** [comment]
Thank you for your answers. I hope one day, it will be possible because I think it's a good feature :)
[Zabbix_Docker_Template.txt](https://github.com/monitoringartist/zabbix-docker-monitoring/files/284107/Zabbix_Docker_Template.txt)

**Comment by jangaraj** [comment]
Please try to compile branch https://github.com/monitoringartist/zabbix-docker-monitoring/tree/systemhostname, my test:
```
jan@dockerhost$ zabbix_get -s 127.0.0.1 -k docker.discovery
{"data":[{"{#FCONTAINERID}":"bc2a8e0c9b7af7048ae452b14540975e6b657b68fa6e1c1c66e60bb0933b7e73","{#SCONTAINERID}":"bc2a8e0c9b7a","{#SYSTEM.HOSTNAME}":"dockerhost","{#HCONTAINERID}":"awesome_mahavira"}]}
```
`{#SYSTEM.HOSTNAME}` has been added.

**Comment by tibo43** [comment]
I tried. Except few warnings, the compile was ok. But, unfortunately, I don't have the same result that you:
```bash
root@debian:~#  zabbix_get -s 192.168.56.101 -k docker.discovery {"data": {"{#FCONTAINERID}":"3676e16f09d0845251183edb64c3bf58da016ec2772037128fc390275e492a68","{#SCONTAINERID}":"3676e16f09d0","{#HCONTAINERID}":"busybox2"}, "{#FCONTAINERID}":"0593038ca0c6767d3928ff55e3192e3683e99b477b440c3fddb6b7facd2d6471","{#SCONTAINERID}":"0593038ca0c6","{#HCONTAINERID}":"busybox1"}, `"{#FCONTAINERID}":"c208e04a1b7f9f3587c7e12ee3e332145b1715ac7c06fd25408c3e64e2c7d147","{#SCONTAINERID}":"c208e04a1b7f","{#HCONTAINERID}":"CoreOS"}]}
```

**Comment by jangaraj** [comment]
Did you compile branch systemhostname (https://github.com/monitoringartist/zabbix-docker-monitoring/tree/systemhostname). It's still not merged in the master branch.

**Comment by tibo43** [comment]
Yes I did. But my copy/paste did not work. I don't know why...
Now, it's working : 
```bash
root@debian:~# zabbix_get -s 192.168.56.101 -k docker.discovery
{"data":[{"{#FCONTAINERID}":"d08bb6f9de552334ec677114dfbff702bf4ec2764918ff58f172331d64c32b09","{#SCONTAINERID}":"d08bb6f9de55","{#SYSTEM.HOSTNAME}":"CoreOS_agent","{#HCONTAINERID}":"CoreOS"},{"{#FCONTAINERID}":"3676e16f09d0845251183edb64c3bf58da016ec2772037128fc390275e492a68","{#SCONTAINERID}":"3676e16f09d0","{#SYSTEM.HOSTNAME}":"CoreOS_agent","{#HCONTAINERID}":"busybox2"},{"{#FCONTAINERID}":"0593038ca0c6767d3928ff55e3192e3683e99b477b440c3fddb6b7facd2d6471","{#SCONTAINERID}":"0593038ca0c6","{#SYSTEM.HOSTNAME}":"CoreOS_agent","{#HCONTAINERID}":"busybox1"}]}
```
It's working on the 
![result1](https://cloud.githubusercontent.com/assets/6716974/15602612/934ff340-23f6-11e6-95c6-9d9a38b3f24e.png)

Thank you for your help :)
Your project is very cool :+1: 
Dashboard of Zabbix:

**Comment by jangaraj** [comment]
Done: merged, CI green, monitoringartist/zabbix-agent-xxl-limited:latest updated

Could you please review template https://github.com/monitoringartist/zabbix-docker-monitoring/blob/master/template/Zabbix-Template-App-Docker-as-host%283.x-only%29.xml ?
Thanks!
