### ISSUE TITLE
Zabbix Agent on start up, the logs don't show libzbxpgsql.so module

### ISSUE THREAD

**Issue by arvindpai** [monitoringartist/zabbix-docker-monitoring#48]
Hi Jan,

I have setup zabbix agent using a docker . The container starts up fine. however need to monitor PostgreSQL which too is a container on Docker .
I made config changes to zabbix_agentd.conf file and provided the load module path as well as load module name in that conf file.

However on starting of Zabbix agent process in the container, it does not load that PostgreSQL module, result I am not able to monitor the db processes using the Zabbix agent.

Here's the snippet of that log 

     8:20160614:001116.170 Starting Zabbix Agent [xx.xx.xx.xx] Zabbix 3.0.3 XXL (2016-05-29) (revision {ZABBIX_REVISION}).
     8:20160614:001116.170 **** Enabled features ****
     8:20160614:001116.170 IPv6 support:          YES
     8:20160614:001116.170 TLS support:           YES
     8:20160614:001116.170 **************************
     8:20160614:001116.170 using configuration file: /etc/zabbix/zabbix_agentd.conf
     8:20160614:001116.173 loaded modules: zabbix_module_docker.so, zabbix_module_stress.so
     8:20160614:001116.173 agent #0 started [main process]
    12:20160614:001116.174 agent #4 started [listener #3]
     9:20160614:001116.175 agent #1 started [collector]
    10:20160614:001116.176 agent #2 started [listener #1]
    11:20160614:001116.177 agent #3 started [listener #2]

This was the command run  
docker run --name=zabbix-agent_test -h hostname -p 10050:10050 -v /:/rootfs -e "ZA_Server=xx.xx.xx.xx" -d monitoringartist/zabbix-agent-xxl-limited:latest

**Comment by jangaraj** [comment]
It's should be issue of another project - https://github.com/monitoringartist/zabbix-agent-xxl. But answer is already there in the README:

> Some settings are excluded and you can't override them: AllowRoot, LoadModulePath, LoadModule, LogType ...

=> Docker image `monitoringartist/zabbix-agent-xxl-limited` doesn't support any additional modules. It's only for Docker monitoring. Paid image `monitoringartist/zabbix-agent-xxl` will support it.

**Comment by arvindpai** [comment]
Hi Jan,

What is the rate of the paid image ?

Thanks,
Arvind

On Monday, June 13, 2016, Jan Garaj <notifications@github.com> wrote:

> It's should be issue of another project -
> https://github.com/monitoringartist/zabbix-agent-xxl. But answer is
> already there in the README:
>
> Some settings are excluded and you can't override them: AllowRoot,
> LoadModulePath, LoadModule, LogType ...
>
> => Docker image monitoringartist/zabbix-agent-xxl-limited doesn't support
> any additional modules. It's only for Docker monitoring. Paid image
> monitoringartist/zabbix-agent-xxl will support it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/monitoringartist/zabbix-docker-monitoring/issues/48#issuecomment-225753324>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQ9s1beuw-3NS6svll6necbDjCv03pi5ks5qLf6ogaJpZM4I03SF>
> .
>


-- 
Sent from my IPhone

**Comment by jangaraj** [comment]
This is off topic Arvind. Please take it offline and send your requirements to info@monitoringartist.com please.
