### ISSUE TITLE
Option to generate the discovered docker instances as new hosts

### ISSUE THREAD

**Issue by ptempier** [monitoringartist/zabbix-docker-monitoring#50]
Hello

Could it be possible to have a template or a script to create the docker instances as new zabbix hosts.
So we don t lose their stats when they migrate to a new host, we can search for docker images in zabbix and that avoid to get a single host with a ton of stats.

**Comment by jangaraj** [comment]
Please use - https://github.com/monitoringartist/zabbix-docker-monitoring/blob/master/template/Zabbix-Template-App-Docker-as-host%283.x-only%29.xml

**Comment by ptempier** [comment]
Thanks a lot
