### ISSUE TITLE
better release management

### ISSUE THREAD

**Issue by ptempier** [monitoringartist/zabbix-docker-monitoring#51]
Hello

Could we have a small changelog with every release

Possibly a more verbose description of the module version being loaded in the zabbix agent logs, to know if it s worth or not updating it ?
Like : docker_module v2.1 for zabbix 3.0 64b

**Comment by jangaraj** [comment]
Unfortunately there is no real release management for now: no tagging, no releases. Only version number in the code is updated.

`for zabbix 3.0 64b` - this is based on compilation and used source code. It's possible to add it, but it'll complicate compilation process.

**Comment by ptempier** [comment]
First part is to track down when to update or not the modules.
I started wanting to use md5 hashes of the modules to check if i needed to update the agent (track a list of old md5 or one good md5). But the new versions are released very fast so it s not practical.

Si i'd be glad if even not using a major.minor schema, you coud use some incremental number or date like YYYYMMMDD and use that as a version string.

Second part was to check whether the modules will be compatible with the zabbix version.
Some zabbix  modules can load in a different zabbix agent that the one they are coded for.. 
Agent works for some time , then crashes or stop responding or only the active/passive part get stucks.

**Comment by jangaraj** [comment]
> Si i'd be glad if even not using a major.minor schema, you coud use some incremental number or date like YYYYMMMDD and use that as a version string.

I don't see any additional value to change it. major.minor schema is common schema.

Binary version is only for lazy admins (included me). But if you have any problem, then you should to always compile own version. It doesn't depend only on Zabbix version, but there can be also problem with libc (glibc, musl) libraries, which can be different per machine/OS. There is not any bulletproof concept, how to check compatibility. I recommend to setup your own compilation process, which will fit your requirements.

**Comment by zhsh87** [comment]
when docker version is up to 1.9 ,  this dir /var/run/netns  had change to /var/run/docker/netns/. So, some key ,such as docker.xnet  will need to change.

**Comment by jangaraj** [comment]
Thx @zhsh87,

Could you open new issue about netns please?
It will need some generic solution, not hardcoded path.

Thanks!

**Comment by jangaraj** [comment]
[changelog.md](https://github.com/monitoringartist/zabbix-docker-monitoring/blob/master/changelog.md) has been added.
