### ISSUE TITLE
zabbix server - Lack of free swap space on Zabbix server

### ISSUE THREAD

**Issue by kwetiaw** [monitoringartist/zabbix-docker-monitoring#52]
Hi there

I'm using docker zabbix XXL and have been getting this issue of Lack of free swap space on Zabbix server. 

My environment, Docker on Oracle Virtualbox on Windows Server 2012. Docker is installed with default settings (no modification done). 

Default Docker Machine has 1 GB Base Memory. Is this the root cause? If I increase it, will it solve the problem?

How do I fix this?

Thanks for your help.

**Comment by jangaraj** [comment]
That's not a Zabbix Docker monitoring issue, but problem of your Zabbix configuration. Please read doc https://www.zabbix.com/documentation/3.0/start or use http://zabbix.org/wiki/Getting_help
