### ISSUE TITLE
unsupported module "zabbix_module_docker.so" version: 1

### ISSUE THREAD

**Issue by ptempier** [monitoringartist/zabbix-docker-monitoring#54]
Hello

The module wont load since 3.2

 19198:20160926:141504.448 Starting Zabbix Agent [raaabbb]. Zabbix 3.2.0 (revision 62485).
 19198:20160926:141504.448 **** Enabled features ****
 19198:20160926:141504.448 IPv6 support:          YES
 19198:20160926:141504.448 TLS support:           YES
 19198:20160926:141504.448 **************************
 19198:20160926:141504.448 using configuration file: /etc/zabbix/zabbix_agentd.conf
 19198:20160926:141504.448 unsupported module "zabbix_module_docker.so" version: 1
 19198:20160926:141504.448 loading modules failed, exiting...

[14:18:24] root@raaabbb - /usr/lib/modules> ls -l /usr/lib/modules/zabbix_module_docker.so
-rw-r--r-- 1 root root 86567 26 sept. 14:10 /usr/lib/modules/zabbix_module_docker.so

[14:19:39] root@raaabbb - /usr/lib/modules> md5sum  /usr/lib/modules/zabbix_module_docker.so
da4de4b955d7aa46524c770f36ff20b1  /usr/lib/modules/zabbix_module_docker.so

[14:19:46] root@raaabbb - /usr/lib/modules> uname -a
Linux raaabbb 4.7.4-1-ARCH #1 SMP PREEMPT Thu Sep 15 15:24:29 CEST 2016 x86_64 GNU/Linux

[14:19:52] root@raaabbb - /usr/lib/modules> cat /etc/lsb-release 
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

**Comment by jangaraj** [comment]
Did you compile version for 3.2?

**Comment by jangaraj** [comment]
I found it - api version has been changed. Try 3.2 branch (quick fix for 3.2).
