### ISSUE TITLE
ZBX_NOTSUPPORTED: Docker's socket API is not avalaible

### ISSUE THREAD

**Issue by helli0n** [monitoringartist/zabbix-docker-monitoring#55]
It doesn't work

```
root@admin1-VirtualBox:~# zabbix_get -s 127.0.0.1  -k docker.info[info]
ZBX_NOTSUPPORTED: Docker's socket API is not avalaible
```

```
root@admin1-VirtualBox:~# echo -e "GET /containers/json?all=0 HTTP/1.0\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Content-Type: application/json
Server: Docker/1.12.1 (linux)
Date: Mon, 10 Oct 2016 14:47:45 GMT

[{"Id":"546d2e0d6f978e62a78a56974697af44f3fa48492d3b8a1e84167ac12678ca3b","Names":["/shipyard-proxy"],"Image":"shipyard/docker-proxy:latest","ImageID":"sha256:cfee14e5d6f280892b9fb16e830aae5c9458e61a7502048ac45b6b1723e8b0b9","Command":"/usr/local/bin/run","Created":1476099299,"Ports":[{"IP":"0.0.0.0","PrivatePort":2375,"PublicPort":2375,"Type":"tcp"}],"Labels":{},"State":"running","Status":"Up 3 hours","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"6871dbb0e5a930e8f7811d10d2c544d0e23ad6929b1a68614b25d2428a4d6bd4","EndpointID":"a012b54196b5f5f914f891209ef001411c6b120a8c63d21e2b36fb1cbf473251","Gateway":"172.17.0.1","IPAddress":"172.17.0.7","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:07"}}},"Mounts":[{"Source":"/var/run/docker.sock","Destination":"/var/run/docker.sock","Mode":"","RW":true,"Propagation":"rprivate"}]},{"Id":"6746ab65f5885e1e4a6e088ec30e4b63301c5efee796ee6525c88c8db92db34a","Names":["/swarm-agent"],"Image":"swarm:latest","ImageID":"sha256:942fd5fd357e2fe2fcecbaf3dd77c313f22ce18a84a5a4d288c0df407a61e623","Command":"/swarm join --addr 10.25.14.152:2375 consul://10.25.14.152:8500","Created":1476099248,"Ports":[{"PrivatePort":2375,"Type":"tcp"}],"Labels":{},"State":"running","Status":"Up 3 hours","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"6871dbb0e5a930e8f7811d10d2c544d0e23ad6929b1a68614b25d2428a4d6bd4","EndpointID":"b61115b79474165b101a7fedcd360644700e63d60c7f9fafde3a9284eab6fc84","Gateway":"172.17.0.1","IPAddress":"172.17.0.3","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:03"}}},"Mounts":[{"Name":"8e237f411f83907fb6e3d5a643fc814cf31c952eb40ca017eca5d1bb119bfe4f","Source":"/var/lib/docker/volumes/8e237f411f83907fb6e3d5a643fc814cf31c952eb40ca017eca5d1bb119bfe4f/_data","Destination":"/.swarm","Driver":"local","Mode":"","RW":true,"Propagation":""}]},{"Id":"b0e95ada12d56940d58ef8e4a0574436dbf8f40710d891594b2114cc85ec8e41","Names":["/shipyard-controller"],"Image":"shipyard/shipyard:latest","ImageID":"sha256:36fb3dc0907d7cdf5536e7f5e5f8aae6763e0dda7e0e3441bdb5b71043d2f250","Command":"/bin/controller server -d tcp://10.25.14.152:3375","Created":1476099170,"Ports":[{"IP":"0.0.0.0","PrivatePort":8080,"PublicPort":8080,"Type":"tcp"}],"Labels":{},"State":"running","Status":"Up 3 hours","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"6871dbb0e5a930e8f7811d10d2c544d0e23ad6929b1a68614b25d2428a4d6bd4","EndpointID":"fb72a3ab39be0b8e70eac6e5d1d809f4ca7524a4ed6470df615b1439694a5fee","Gateway":"172.17.0.1","IPAddress":"172.17.0.6","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:06"}}},"Mounts":[]},{"Id":"8a3e55093f47cb35bcee0b87af666223d778d511ba1ba138bd8b77559014f666","Names":["/shipyard-rethinkdb","/shipyard-controller/rethinkdb"],"Image":"rethinkdb","ImageID":"sha256:d10cc6435528da5d3018dd5dd65768fb01b5be930e53e225cd39ed126b00f3bc","Command":"rethinkdb --bind all","Created":1476099167,"Ports":[{"PrivatePort":28015,"Type":"tcp"},{"PrivatePort":8080,"Type":"tcp"},{"PrivatePort":29015,"Type":"tcp"}],"Labels":{},"State":"running","Status":"Up 3 hours","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"6871dbb0e5a930e8f7811d10d2c544d0e23ad6929b1a68614b25d2428a4d6bd4","EndpointID":"b2d508160f39f026abd052062f95c27e56b7f092358edd29aba4aaf6207e9224","Gateway":"172.17.0.1","IPAddress":"172.17.0.5","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:05"}}},"Mounts":[{"Name":"da89f95e128f0d1932f0e79c565a6d7db4a9ab8e89d5046e79a9ed066c47c273","Source":"/var/lib/docker/volumes/da89f95e128f0d1932f0e79c565a6d7db4a9ab8e89d5046e79a9ed066c47c273/_data","Destination":"/data","Driver":"local","Mode":"","RW":true,"Propagation":""}]},{"Id":"fcc964a9bb375f2a513373c49a7ae60380b6e0fc02f9592d0d9ca60bc083c663","Names":["/swarm-manager","/shipyard-controller/swarm"],"Image":"swarm:latest","ImageID":"sha256:942fd5fd357e2fe2fcecbaf3dd77c313f22ce18a84a5a4d288c0df407a61e623","Command":"/swarm manage --host tcp://0.0.0.0:3375 consul://10.25.14.152:8500","Created":1476099124,"Ports":[{"IP":"0.0.0.0","PrivatePort":3375,"PublicPort":3375,"Type":"tcp"},{"PrivatePort":2375,"Type":"tcp"}],"Labels":{},"State":"running","Status":"Up 3 hours","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"6871dbb0e5a930e8f7811d10d2c544d0e23ad6929b1a68614b25d2428a4d6bd4","EndpointID":"5dea8565b3d4b3c4b86d4c842ddca3b50485dc7d09944c86f151e9da69899323","Gateway":"172.17.0.1","IPAddress":"172.17.0.4","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:04"}}},"Mounts":[{"Name":"b43577308881597a353a4f372375f32e289186f1b2822a1b94853d882d8b9e72","Source":"/var/lib/docker/volumes/b43577308881597a353a4f372375f32e289186f1b2822a1b94853d882d8b9e72/_data","Destination":"/.swarm","Driver":"local","Mode":"","RW":true,"Propagation":""}]},{"Id":"1fe4fe89357ddd701a09eb43bb3c7a67618e4c2fd6b7027a154f07fd99568d1b","Names":["/consul"],"Image":"progrium/consul","ImageID":"sha256:09ea64205e553163a9d7790c9688cff73e3dc2439a8382021a2b2223545f01ff","Command":"/bin/start -server -bootstrap","Created":1476099099,"Ports":[{"PrivatePort":8300,"Type":"tcp"},{"PrivatePort":53,"Type":"tcp"},{"IP":"0.0.0.0","PrivatePort":8500,"PublicPort":8500,"Type":"tcp"},{"PrivatePort":8400,"Type":"tcp"},{"PrivatePort":8302,"Type":"tcp"},{"PrivatePort":8301,"Type":"tcp"},{"PrivatePort":8302,"Type":"udp"},{"PrivatePort":8301,"Type":"udp"},{"PrivatePort":53,"Type":"udp"}],"Labels":{},"State":"running","Status":"Up 3 hours","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"6871dbb0e5a930e8f7811d10d2c544d0e23ad6929b1a68614b25d2428a4d6bd4","EndpointID":"95a7f2fa149949793ae4fcfd7b1de7f0ab822a28d74fbb54f7e22d2b5695c7c6","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}},"Mounts":[{"Name":"8d90c1bbebe7642c0e4e4a209092772322677eddba07ee214384ed497190940d","Source":"/var/lib/docker/volumes/8d90c1bbebe7642c0e4e4a209092772322677eddba07ee214384ed497190940d/_data","Destination":"/data","Driver":"local","Mode":"","RW":true,"Propagation":""}]}]
```
```
root@admin1-VirtualBox:~# uname -a
Linux admin1-VirtualBox 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@admin1-VirtualBox:~# docker -v
Docker version 1.12.1, build 23cf638
```
```
root@admin1-VirtualBox:~# zabbix_agentd -V
zabbix_agentd (daemon) (Zabbix) 3.0.5
Revision 62889 30 September 2016, compilation time: Oct  2 2016 16:05:32

Copyright (C) 2016 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

```

I can't find issue, please help me

**Comment by jangaraj** [comment]
How did you install/compile module?

**Comment by helli0n** [comment]
I have tried both, and it has the same issue

**Comment by jangaraj** [comment]
OK. How did you compile and install module? Question is _how_? Increase zabbix-agent log level and check zabbix log.

**Comment by helli0n** [comment]
> 19196:20161010:181450.237 Zabbix Agent stopped. Zabbix 3.0.5 (revision 62889).
>  19436:20161010:181450.266 Starting Zabbix Agent [localhost]. Zabbix 3.0.5 (revision 62889).
>  19436:20161010:181450.266 **** Enabled features ****
>  19436:20161010:181450.266 IPv6 support:          YES
>  19436:20161010:181450.266 TLS support:           YES
>  19436:20161010:181450.266 **************************
>  19436:20161010:181450.266 using configuration file: /etc/zabbix/zabbix_agentd.conf
>  19436:20161010:181450.266 In load_modules()
>  19436:20161010:181450.266 loading module "/usr/lib/zabbix/modules/zabbix_module_docker.so"
>  19436:20161010:181450.267 In zbx_module_api_version()
>  19436:20161010:181450.267 In zbx_module_init()
>  19436:20161010:181450.267 zabbix_module_docker v0.6.4, compilation time: Sep 26 2016 21:29:18
>  19436:20161010:181450.267 In zbx_docker_dir_detect()
>  19436:20161010:181450.267 Detected docker stat directory: /sys/fs/cgroup/
>  19436:20161010:181450.267 Detected used docker driver dir: docker/
>  19436:20161010:181450.267 Detected JoinController cpu,cpuacct
>  19436:20161010:181450.267 In zbx_docker_api_detect()
>  19436:20161010:181450.267 In zbx_docker_perm()
>  19436:20161010:181450.267 Additional permission of Zabbix Agent are not detected - only basic docker metrics are available
>  19436:20161010:181450.267 In zbx_module_item_timeout()
>  19436:20161010:181450.267 In register_module()
>  19436:20161010:181450.267 End of register_module():SUCCEED
>  19436:20161010:181450.267 In zbx_module_item_list()
>  19436:20161010:181450.267 loading module "/usr/lib/zabbix/modules/zabbix_module_docker.so"
>  19436:20161010:181450.267 In zbx_module_api_version()
>  19436:20161010:181450.267 In zbx_module_init()
>  19436:20161010:181450.267 zabbix_module_docker v0.6.4, compilation time: Sep 26 2016 21:29:18
>  19436:20161010:181450.267 In zbx_docker_dir_detect()
>  19436:20161010:181450.267 Detected docker stat directory: /sys/fs/cgroup/
>  19436:20161010:181450.267 Detected used docker driver dir: docker/
>  19436:20161010:181450.267 Detected JoinController cpu,cpuacct
>  19436:20161010:181450.267 In zbx_docker_api_detect()
>  19436:20161010:181450.267 In zbx_docker_perm()
>  19436:20161010:181450.267 Additional permission of Zabbix Agent are not detected - only basic docker metrics are available
> 19436:20161010:181450.267 In zbx_module_item_timeout()
>  19436:20161010:181450.267 In register_module()
>  19436:20161010:181450.267 End of register_module():FAIL
>  19436:20161010:181450.267 loaded modules: zabbix_module_docker.so
>  19436:20161010:181450.267 End of load_modules():SUCCEED
>  19436:20161010:181450.267 In init_collector_data()
>  19436:20161010:181450.269 In zbx_dshm_create() proj_id:112 size:0
>  19436:20161010:181450.269 End of zbx_dshm_create():SUCCEED shmid:-1
>  19436:20161010:181450.269 End of init_collector_data()
>  19436:20161010:181450.269 agent #0 started [main process]
>  19449:20161010:181450.270 agent #4 started [listener #3]
>  19449:20161010:181450.270 In zbx_tls_init_child()
>  19448:20161010:181450.273 agent #3 started [listener #2]
>  19448:20161010:181450.273 In zbx_tls_init_child()
>  19450:20161010:181450.280 agent #5 started [active checks #1]
>  19450:20161010:181450.280 In zbx_tls_init_child()
>  19450:20161010:181450.282 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
>  19450:20161010:181450.282 End of zbx_tls_init_child()
>  19450:20161010:181450.282 In init_active_metrics()
>  19450:20161010:181450.282 buffer: first allocation for 100 elements
>  19450:20161010:181450.282 End of init_active_metrics()
>  19450:20161010:181450.282 In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
>  19450:20161010:181450.282 End of send_buffer():SUCCEED
>  19450:20161010:181450.282 __zbx_zbx_setproctitle() title:'active checks #1 [getting list of active checks]'
>  19450:20161010:181450.282 In refresh_active_checks() host:'127.0.0.1' port:10051
>  19447:20161010:181450.282 agent #2 started [listener #1]
>  19447:20161010:181450.282 In zbx_tls_init_child()
>  19447:20161010:181450.283 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
>  19447:20161010:181450.283 End of zbx_tls_init_child()
>  19447:20161010:181450.283 __zbx_zbx_setproctitle() title:'listener #1 [waiting for connection]'
>  19446:20161010:181450.283 agent #1 started [collector]
>  19446:20161010:181450.283 In init_cpu_collector()
>  19446:20161010:181450.283 End of init_cpu_collector():SUCCEED
>  19446:20161010:181450.283 __zbx_zbx_setproctitle() title:'collector [processing data]'
>  19446:20161010:181450.283 In update_cpustats()
>  19446:20161010:181450.283 End of update_cpustats()
>  19446:20161010:181450.283 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
>  19449:20161010:181450.284 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
>  19449:20161010:181450.284 End of zbx_tls_init_child()
>  19449:20161010:181450.284 __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
>  19450:20161010:181450.284 active check configuration update from [127.0.0.1:10051] started to fail (cannot connect to [[127.0.0.1]:10051]: [111] Connection refused)
>  19450:20161010:181450.284 End of refresh_active_checks():FAIL
>  19450:20161010:181450.284 __zbx_zbx_setproctitle() title:'active checks #1 [processing active checks]'
>  19450:20161010:181450.284 In process_active_checks() server:'127.0.0.1' port:10051
>  19450:20161010:181450.284 End of process_active_checks()
>  19450:20161010:181450.284 In get_min_nextcheck()
>  19450:20161010:181450.284 End of get_min_nextcheck():-1
>  19450:20161010:181450.284 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
>  19448:20161010:181450.285 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
> 19436:20161010:181450.267 In zbx_module_item_timeout()
>  19436:20161010:181450.267 In register_module()
>  19436:20161010:181450.267 End of register_module():FAIL
>  19436:20161010:181450.267 loaded modules: zabbix_module_docker.so
>  19436:20161010:181450.267 End of load_modules():SUCCEED
>  19436:20161010:181450.267 In init_collector_data()
>  19436:20161010:181450.269 In zbx_dshm_create() proj_id:112 size:0
>  19436:20161010:181450.269 End of zbx_dshm_create():SUCCEED shmid:-1
>  19436:20161010:181450.269 End of init_collector_data()
>  19436:20161010:181450.269 agent #0 started [main process]
>  19449:20161010:181450.270 agent #4 started [listener #3]
>  19449:20161010:181450.270 In zbx_tls_init_child()
>  19448:20161010:181450.273 agent #3 started [listener #2]
>  19448:20161010:181450.273 In zbx_tls_init_child()
>  19450:20161010:181450.280 agent #5 started [active checks #1]
>  19450:20161010:181450.280 In zbx_tls_init_child()
>  19450:20161010:181450.282 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
>  19450:20161010:181450.282 End of zbx_tls_init_child()
>  19450:20161010:181450.282 In init_active_metrics()
>  19450:20161010:181450.282 buffer: first allocation for 100 elements
>  19450:20161010:181450.282 End of init_active_metrics()
>  19450:20161010:181450.282 In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
>  19450:20161010:181450.282 End of send_buffer():SUCCEED
>  19450:20161010:181450.282 __zbx_zbx_setproctitle() title:'active checks #1 [getting list of active checks]'
>  19450:20161010:181450.282 In refresh_active_checks() host:'127.0.0.1' port:10051
>  19447:20161010:181450.282 agent #2 started [listener #1]
>  19447:20161010:181450.282 In zbx_tls_init_child()
>  19447:20161010:181450.283 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
>  19447:20161010:181450.283 End of zbx_tls_init_child()
>  19447:20161010:181450.283 __zbx_zbx_setproctitle() title:'listener #1 [waiting for connection]'
>  19446:20161010:181450.283 agent #1 started [collector]
>  19446:20161010:181450.283 In init_cpu_collector()
>  19446:20161010:181450.283 End of init_cpu_collector():SUCCEED
>  19446:20161010:181450.283 __zbx_zbx_setproctitle() title:'collector [processing data]'
>  19446:20161010:181450.283 In update_cpustats()
>  19446:20161010:181450.283 End of update_cpustats()
>  19446:20161010:181450.283 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
>  19449:20161010:181450.284 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
>  19449:20161010:181450.284 End of zbx_tls_init_child()
>  19449:20161010:181450.284 __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
>  19450:20161010:181450.284 active check configuration update from [127.0.0.1:10051] started to fail (cannot connect to [[127.0.0.1]:10051]: [111] Connection refused)
>  19450:20161010:181450.284 End of refresh_active_checks():FAIL
>  19450:20161010:181450.284 __zbx_zbx_setproctitle() title:'active checks #1 [processing active checks]'
>  19450:20161010:181450.284 In process_active_checks() server:'127.0.0.1' port:10051
>  19450:20161010:181450.284 End of process_active_checks()
>  19450:20161010:181450.284 In get_min_nextcheck()
>  19450:20161010:181450.284 End of get_min_nextcheck():-1
>  19450:20161010:181450.284 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
>  19448:20161010:181450.285 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
>  19449:20161010:181450.284 End of zbx_tls_init_child()
>  19449:20161010:181450.284 __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
>  19450:20161010:181450.284 active check configuration update from [127.0.0.1:10051] started to fail (cannot connect to [[127.0.0.1]:10051]: [111] Connection refused)
>  19450:20161010:181450.284 End of refresh_active_checks():FAIL
>  19450:20161010:181450.284 __zbx_zbx_setproctitle() title:'active checks #1 [processing active checks]'
>  19450:20161010:181450.284 In process_active_checks() server:'127.0.0.1' port:10051
>  19450:20161010:181450.284 End of process_active_checks()
>  19450:20161010:181450.284 In get_min_nextcheck()
>  19450:20161010:181450.284 End of get_min_nextcheck():-1
>  19450:20161010:181450.284 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
>  19448:20161010:181450.285 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
>  19448:20161010:181450.285 End of zbx_tls_init_child()
>  19448:20161010:181450.285 __zbx_zbx_setproctitle() title:'listener #2 [waiting for connection]'
>  19446:20161010:181451.283 __zbx_zbx_setproctitle() title:'collector [processing data]'
>  19446:20161010:181451.284 In update_cpustats()
>  19446:20161010:181451.284 End of update_cpustats()
>  19446:20161010:181451.284 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
>  19450:20161010:181451.284 In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
>  19450:20161010:181451.284 End of send_buffer():SUCCEED
>  19450:20161010:181451.284 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
>  19449:20161010:181451.968 __zbx_zbx_setproctitle() title:'listener #3 [processing request]'
>  19449:20161010:181451.968 Requested [docker.info[info]]
>  19449:20161010:181451.968 In zbx_module_docker_info()
>  19449:20161010:181451.969 In zbx_docker_api_detect()
>  19449:20161010:181451.969 In zbx_docker_perm()
>  19449:20161010:181451.969 Additional permission of Zabbix Agent are not detected - only basic docker metrics are available
>  19449:20161010:181451.969 Docker's socket API is not avalaible
>  19449:20161010:181451.969 Sending back [ZBX_NOTSUPPORTED: Docker's socket API is not avalaible]
>  19449:20161010:181451.969 __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
>  19446:20161010:181452.284 __zbx_zbx_setproctitle() title:'collector [processing data]'
>  19446:20161010:181452.284 In update_cpustats()
>  19446:20161010:181452.284 End of update_cpustats()
>  19446:20161010:181452.284 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
>  19450:20161010:181452.285 In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
>  19450:20161010:181452.285 End of send_buffer():SUCCEED
>  19450:20161010:181452.285 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
>  19450:20161010:181453.285 In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
>  19450:20161010:181453.285 End of send_buffer():SUCCEED
>  19450:20161010:181453.285 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
>  19446:20161010:181453.285 __zbx_zbx_setproctitle() title:'collector [processing data]'
>  19446:20161010:181453.285 In update_cpustats()
>  19446:20161010:181453.285 End of update_cpustats()
>  19446:20161010:181453.285 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
>

**Comment by jangaraj** [comment]
> Additional permission of Zabbix Agent are not detected - only basic docker metrics are available
Run zabbix agent as root. Docker socket needs root permission!

**Comment by helli0n** [comment]
Thanks!

**Comment by sebruant** [comment]
> > Additional permission of Zabbix Agent are not detected - only basic docker metrics are available
> 
> Run zabbix agent as root. Docker socket needs root permission!
> 
> https://github.com/monitoringartist/zabbix-docker-monitoring#additional-docker-permissions

LOL, do this pls @helli0n.  Try  "usermod -aG docker zabbix" and restart zabbix-agent2 rather than adding root permissions to agent.
