### ISSUE TITLE
Running agent blocks remove of containers

### ISSUE THREAD

**Issue by siedi** [monitoringartist/zabbix-docker-monitoring#57]
We start our containers via systemd services (typical flow is: prestart: kill, remove, pull, then start, stop is just stop). 
After the running containers are discovered by the agent, we cannot restart the container any more. Actually the remove fails as docker claims that some files are still in use.  Once we stop the agent, the removal works again. 
Is it possible to trigger the agent to release any locks on those files once the container is stopped?

**Comment by jangaraj** [comment]
Please provide procedure how to replicate your issue.

**Comment by siedi** [comment]
Seems like it is a known issue, e.g. https://github.com/docker/docker/issues/20560

Steps to reproduce:
1. Start zabbix-agent-xxl-limited:latest
$ /usr/bin/docker run --network=zabbix_nw --name zabbix-agent -e "ZA_Server=zabbix" -h %H -p 20050:10050 -v /:/rootfs -v /var/run:/var/run monitoringartist/zabbix-agent-xxl-limited:latest

2. Start another docker container
$ /usr/bin/docker run --network=zabbix_nw --name jupiter-tunnel siedi/zabbix-autossh zabbixagent@<somehost>

3. Wait some time till the container is shown in Zabbix

4. Stop container
$ /usr/bin/docker stop -t 2 jupiter-tunnel

5. Remove container
$ /usr/bin/docker rm jupiter-tunnel

Error response from daemon: Unable to remove filesystem for 2227faecfc0d451554de9310549a6b675927e1606748b77c58a96d919db48402: remove /var/lib/docker/containers/2227faecfc0d451554de9310549a6b675927e1606748b77c58a96d919db48402/shm: device or resource busy

6. Stop zabbix-agent
$/usr/bin/docker stop -t 20 zabbix-agent

7. Remove container agin:
$ /usr/bin/docker rm jupiter-tunnel
jupiter-tunnel

Works.

**Comment by jangaraj** [comment]
BTW: that's a different project https://github.com/monitoringartist/zabbix-agent-xxl. By default containerized agent doesn't use any container shared memory (shm). Maybe if you are pulling docker discovery/stats metrics `docker.stats[]`, then docker daemon utilizes also container shm. I don't know. Try to force it `--rm -f`.

**Comment by siedi** [comment]
ok, will try, closing for now

**Comment by jangaraj** [comment]
OK, keep me informed please.
