### ISSUE TITLE
Timeout while executing operation.

### ISSUE THREAD

**Issue by Tairy** [monitoringartist/zabbix-docker-monitoring#60]
Hello, I was using `zabbix-docker-monitoring plugin`. But I got an error:

```
 Get value from agent failed: ZBX_TCP_READ() timed out
```
when the `zabbix_agent` run for a while. 

Could you give me some advice to solve it.

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/zabbix-docker-monitoring#troubleshooting

**Comment by jangaraj** [comment]
Closing, no user input.
