### ISSUE TITLE
Docker 1.12 support

### ISSUE THREAD

**Issue by galindro** [monitoringartist/zabbix-docker-monitoring#61]
Is this monitoring module supports Docker 1.12 swarm mode?

**Comment by jangaraj** [comment]
That's not correct question. This module monitors only Docker containers. Swarm is only additional layer on top of containers. Yes, it can monitor your container also if you use swarm + no - you can't monitor swarm metrics, because they are not container metrics.

**Comment by galindro** [comment]
It isn't the focus of this project to provide swarm metrics besides container metrics?

**Comment by jangaraj** [comment]
No, swarm is only orchestration tools and there is many orchestration tools: Kubernetes, AWS ECS, Control Center, .... Scope of this project is only single container monitoring. Orchestration metrics maybe will be a part of https://github.com/monitoringartist/zabbix-agent-xxl#paid-zabbix-agent-xxl-docker-image

**Comment by galindro** [comment]
I there any updates about this development and how much it will cost?
As soon Swarm is Docker's official ochestration tool and it has been integrated to docker engine since 1.12.0 version, IMHO you should consider to add it's monitoring on paid-zabbix-agent-xxl-docker-image.

**Comment by jangaraj** [comment]
I've just published [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSdte1irviwtQzXU8_DMzboxf_qggE3qgjgpPHoBlE9RzLCXKA/viewform). Please submit your requirements. If users will require swarm support, then it'll be business reason to implement it. I was looking at swarm API a few days ago and it's possible to integrate it with Zabbix. Thanks.
