### ISSUE TITLE
Can't run on ubuntu 14.04

### ISSUE THREAD

**Issue by thorro** [monitoringartist/zabbix-docker-monitoring#63]
Zabbix 3.2.1 deb's, precompiled or compiled module, I get error:

` 10734:20170111:125709.899 Starting Zabbix Agent [host.prod]. Zabbix 3.2.1 (revision 62890).
 10734:20170111:125709.899 **** Enabled features ****
 10734:20170111:125709.899 IPv6 support:          YES
 10734:20170111:125709.899 TLS support:           YES
 10734:20170111:125709.899 **************************
 10734:20170111:125709.899 using configuration file: /etc/zabbix/zabbix_agentd.conf
 10734:20170111:125709.900 cannot load module "zabbix_module_docker.so": /usr/lib/zabbix/modules/zabbix_module_docker.so: **undefined symbol: zbx_alarm_timed_out**
 10734:20170111:125709.900 loading modules failed, exiting...`

**Comment by jangaraj** [comment]
I guess your zabbix-agent package is specially compiled (`gcc -s`). The safe option is to compile own agent or try use another zabbix-agent package (probably repo.zabbix.com will be good option).

**Comment by roybliss** [comment]
I installed Zabbix agent with "apt-get install" on ubuntu14.04 and got the same problem,  Do I need to change another agent package?

**Comment by jangaraj** [comment]
https://www.zabbix.com/documentation/3.2/manual/installation/install_from_packages/repository_installation
