### ISSUE TITLE
problem of "normalize CPU usage"

### ISSUE THREAD

**Issue by wydream** [monitoringartist/zabbix-docker-monitoring#64]
the code shows that it normalize CPU usage by using number of online CPUs
why not by calculating CpuShares/1024 or CpuQuota/100000 in docker inspect, thats the CPUs container use actually.

**Comment by jangaraj** [comment]
Could you provide some doc/examples please. I don't understand that calculation, so I need more details. Thx.

**Comment by wydream** [comment]
For example, a node with 4CPUs, a container is allocated 2CPUs. Both CPU work as 80% utilization.
cpu_num = sysconf(_SC_NPROCESSORS_ONLN) —— that is 4
So, the final result is 40%. 
I think the 80% is the correct answer. Am I right?

**Comment by jangaraj** [comment]
It's much more complicated. Cpu cgroup v1 limits are work conserving, ie. a task would not be stopped from using cpu if there is no competition.

See doc:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Resource_Management_Guide/sec-cpu.html

And it the be even more complicated with cgroup v2 (cpu limitation is still open topic): maybe you will be able to place cgroup cpu limits per process/thread, not only for container

**Comment by wydream** [comment]
Thanks for reply.

**Comment by jangaraj** [comment]
The best option is to write similar collector as Zabbix agent uses for CPU usage monitoring. It'll be new thread, which will collect cgroup cpu stats periodically (every sec). Then metric request will query only this cpu collector for current calculated (system/user/total, 1sec, 1m, 5m, cpu 1, cpu 2, .....) CPU container usage. Any PR is welcome :-).
