### ISSUE TITLE
agent 3.0 undefined symbol: zbx_alarm_timed_out

### ISSUE THREAD

**Issue by markthornton** [monitoringartist/zabbix-docker-monitoring#65]
I believe this exists in 3.2, but both the precompiled 3.0 library and compiling it myself try to use it.

I am using Ubuntu yakkety with the packaged zabbix 3.0.4.

**Comment by jangaraj** [comment]
I'm not sure what is real reason, but probably your package maintainer is stripping agent binary. Use official packages or compile your own agent and then it'll be ok.

**Comment by markthornton** [comment]
Compiling against the exact version solved the problem

svn export svn://svn.zabbix.com/tags/3.0.4 zabbix-3.0.4
