### ISSUE TITLE
docker.vstatus[All] returning "ZBX_NOTSUPPORTED: Not supported volume state"

### ISSUE THREAD

**Issue by drewmudgett** [monitoringartist/zabbix-docker-monitoring#66]
Howdy,

I'm getting a 'ZBX_NOTSUPPORTED: Not supported volume state' when attempting to query the docker.vstatus metric with the 'All' state specified.  The 'Dangling' state works as expected:

[root@zabbixproxy1 ~]# zabbix_get -s dockerhost1 -k docker.vstatus[All]
ZBX_NOTSUPPORTED: Not supported volume state
[root@zabbixproxy1 ~]# zabbix_get -s dockerhost1 -k docker.vstatus[Dangling]
2

I'm running Zabbix 3.2 and the Docker API version 1.26 on RHEL 7.3.
Thanks

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/zabbix-docker-monitoring#troubleshooting please

**Comment by drewmudgett** [comment]
Howdy,

No different output from the zabbix_get command, but here's the relevant log entries on the agent: 

 37176:20170316:142526.437 In zbx_module_docker_vstatus()
 37176:20170316:142526.437 In zbx_module_docker_socket_query()
 37176:20170316:142526.437 Docker's socket query: GET /volumes HTTP/1.0
 37176:20170316:142526.437 Docker's socket response: {"Volumes":[{"Driver":"local","Labels":null,"Mountpoint":"/var/lib/docker/volumes/dtr-ca-210a4ddb9c97/_data","Name":"dtr-ca-210a4ddc9c87","Options":{},"Scope":"local"},{"Driver":"local","Labels":null,"Mountpoint":"/var/lib/docker/volumes/ucp-auth-api-certs/_data","Name":"ucp-auth-api-certs","Options":{},"Scope":"local"},{"Driver":"local","Labels":null,"Mountpoint":"/var/lib/docker/volumes/ucp-auth-worker-data/_data","Name":"ucp-auth-worker-data","Options":{},"Scope":"local"},{"Driver":"local","Labels":null,"Mountpoint":"/var/lib/docker/volumes/ucp-cluster-root-ca/_data","Name":"ucp-cluster-root-ca","Options":{},"Scope":"local"},{"Driver":"local","Labels":{},"Mountpoint":"/var/lib/docker/volumes/dtr-rethink-56d783eeb360/_data","Name":"dtr-rethink-56d683eeb460","Options":{},"Scope":"local"},{"Driver":"local","Labels":null,"Mountpoint":"/var/lib/docker/volumes/ucp-kv-certs/_data","Name":"ucp-kv-certs","Options":{},"Scope":"local"},{"Driver":"local","Labels":null,"Mountpoint":"/var/lib/docker/volumes/ucp-node-certs/_data","Name":"ucp-node-certs","Options":{},"Scope":"local"},{"Driver":"local","Labels":null,"Mountpoint":"/var/lib/docker/volumes/6958399cdb47cc48ab1809405c254a78e5e5d99a4f50f77f97e5e1eb8fd21b7b/_data","Name":"6958399cdb47cc48ab1809405c254a78e5e5d99a4f50f77f97e5e1eb8fd21b7b","Options":{},"Scope":"local"},{"Driver":"local","Labels":null,"Mountpoint":"/var/lib/docker/volumes/ucp-auth-worker-certs/_data","Name":"ucp-auth-worker-certs","Options":{},"Scope":"local"}],"Warnings":null}
 37176:20170316:142526.437 Not supported volume state: All
 37176:20170316:142526.437 active check "docker.vstatus[All]" is not supported: Not supported volume state
 37176:20170316:142526.437 In process_value() key:'dockerhost1:docker.vstatus[All]' value:'Not supported volume state'
 37176:20170316:142526.437 In send_buffer() host:'zabbixproxy1' port:10051 entries:42/100
 37176:20170316:142526.437 send_buffer() now:1489688726 lastsent:1489688726 now-lastsent:0 BufferSend:5; will not send now
 37176:20170316:142526.437 End of send_buffer():SUCCEED
 37176:20170316:142526.437 buffer: new element 42
 37176:20170316:142526.437 End of process_value():SUCCEED
 37176:20170316:142526.437 End of process_active_checks()
 37176:20170316:142526.437 In get_min_nextcheck()
 37176:20170316:142526.438 End of get_min_nextcheck():1489688727


Thanks

**Comment by jangaraj** [comment]
Thanks. I see the same problem. It needs refactoring of that vstatus method. Dangling value is also incorrect.
```
[root@dockerhost ~]# docker volume ls -q -f dangling=true
09003034c95bc725aad94b6f97061d3f88a0893b45f3354d0a3972b569f3fc42
283ca2a77f605929f2522bcbb1d2500eb7df10d996da967d71cabe534f61d904
2f1ad3a6dd8a0058eb04f8bcdc9b265f699207021e93113ebd71c38bd1049c5b
5f84d03890df091b306909c5f8c347210e4a608188b3fa3a39df841f5d73953d
61df9d732eb6da4fd38eb2903bc4787303baaa05c0b4384a0e662fa73a18ac79
68a5fb0aa32d234f45c772b2dca19a35ca12d3c664192a0e85627b31ec894239
6a1103ec2a5f263d64a1720fea333b198db49e4a826b817ace12c7f8fd40e609
91a6e9222ff5c31bf05080c31b844a39ce38abed74e6ad0c6bc7b93617a13766
9e3bc59955e4e34ff23a1aeff48b3e05aee61e0e61e7aa566d244984bf56814d
[root@dockerhost ~]# zabbix_get -s localhost -k docker.vstatus[Dangling]
2
[root@dockerhost ~]# zabbix_get -s localhost -k docker.vstatus[All]
ZBX_NOTSUPPORTED: Not supported volume state
```

**Comment by jangaraj** [comment]
Fix is in the `vstatus` branch for now - https://github.com/monitoringartist/zabbix-docker-monitoring/tree/vstatus. Please test.

**Comment by drewmudgett** [comment]
Howdy,
Looks great now!  
Thanks!
