### ISSUE TITLE
Move the SELinux policy to a file in the repo

### ISSUE THREAD

**Issue by gregswift** [monitoringartist/zabbix-docker-monitoring#69]
It would be helpful if the SELinux policy was in the GitHub repo so that it would be easier to clone this repo and build out the things. For instance I need to package this up in RPMs for distribution internally, and while I can do it manually, this makes it harder to automate.

**Comment by gregswift** [comment]
thanks!

**Comment by jangaraj** [comment]
@gregswift Could you share your rpm packaging script for inspiration please? (as a gist snippet).
I tried to use FPM for deb/rpm packaging a few months ago, but I gave it up.

**Comment by gregswift** [comment]
well.. i can partialy see why... zabbix RPMs on fedora don't have a devel package which makes this kinda a pita

**Comment by gregswift** [comment]
@jangaraj So finally got back to this.

https://gist.github.com/gregswift/341b59724124f1e47d6bbb4004c7071e 

I still need to add the selinux policy part, which i'll do with a new update to that gist

**Comment by gregswift** [comment]
updated the gist with -2 release that supports selinux policies

**Comment by gregswift** [comment]
Moved it to a [git repo](https://github.com/packit4me/packed-zabbix-agent-module-docker)... if you check that repo out then run `make` it will download artifacts and run the builds.

You can also use mock.. ie:

```
MOCK_REPO=epel-7-x86_64 make mock
```
