### ISSUE TITLE
Cannot open /proc/mounts: [2] No such file or directory

### ISSUE THREAD

**Issue by maadjahangir** [monitoringartist/zabbix-docker-monitoring#70]
Hi,

I am seeing following error with the container items on Zabbix:

`"docker.up/systemd.up check is not available at the moment - no stat directory"`

**Docker run**:
```
docker run --name=dockbix-agent-xxl --net=host --privileged -p 10050:10050 -h $(hostname) -v /:/rootfs  -v /var/run:/var/run --restart unless-stopped -e "ZA_Server=10.9.0.2" -e "ZA_ServerActive=10.9.0.2" -e "ZBX_DEBUGLEVEL=5" --log-driver json-file -d monitoringartist/dockbix-agent-xxl-limited:latest 
```

**Docker logs**  : 
` docker logs -f dockbix-agent-xxl
Dockbix Agent XXL v0.0.1b limited version
Copyright (C) 2014-2017 Jan Garaj - www.monitoringartist.com
Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
Starting Zabbix Agent [monitoring]. Zabbix 3.2.4 Dockbix Agent XXL (2017-03-25) (revision ).
Press Ctrl+C to exit.

    14:20170507:152148.363 Starting Zabbix Agent [monitoring]. Zabbix 3.2.4 Dockbix Agent XXL (2017-03-25) (revision ).
    14:20170507:152148.363 **** Enabled features ****
    14:20170507:152148.363 IPv6 support:          YES
    14:20170507:152148.363 TLS support:            NO
    14:20170507:152148.363 **************************
    14:20170507:152148.363 using configuration file: /etc/zabbix/zabbix_agentd.conf
    14:20170507:152148.364 Cannot open /proc/mounts: [2] No such file or directory
    14:20170507:152148.364 loaded modules: zabbix_module_docker.so, zabbix_module_stress.so
    14:20170507:152148.365 agent #0 started [main process]
    15:20170507:152148.365 agent #1 started [collector]
    16:20170507:152148.365 agent #2 started [listener #1]
    17:20170507:152148.365 agent #3 started [listener #2]
    18:20170507:152148.365 agent #4 started [listener #3]
    19:20170507:152148.366 agent #5 started [active checks #1]
    19:20170507:152148.368 no active checks on server [10.9.0.2:10051]: host [monitoring] not found`

**Debug Says:** 
` docker exec -ti dockbix-agent-xxl zabbix_get -s 10.9.0.2 -k docker.up[\kibana]
ZBX_NOTSUPPORTED: docker.up/systemd.up check is not available at the moment - no stat directory`

Though docker.discovery works fine.

**Docker Info:**
```
docker info
Containers: 20
 Running: 18
 Paused: 0
 Stopped: 2
Images: 76
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-202:1-530624-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 13.22 GB
 Data Space Total: 107.4 GB
 Data Space Available: 94.16 GB
 Metadata Space Used: 15.38 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.132 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.4.44-39.55.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 251.9 GiB
Name: monitoring
ID: NMYF:RQEC:JZ4C:AW5U:7X7F:4FM2:MUO5:C4IL:WZ5S:OI5G:LZFO:Q7VV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: svulfr
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8`
```

**Mount Points**:
```
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devtmpfs on /dev type devtmpfs (rw,relatime,size=132062168k,nr_inodes=33015542,mode=755)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
/dev/xvda1 on / type ext4 (rw,noatime,data=ordered) [/]
/dev/xvdi on /mnt/xvdi type ext4 (rw,relatime,data=ordered)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
cgroup on /cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /cgroup/perf_event type cgroup (rw,relatime,perf_event)

```
`
ls  /sys/fs/cgroup/
`

`ls /cgroup/
blkio  cpu  cpuacct  cpuset  devices  freezer  hugetlb  memory  perf_event
`

Can someone assist if there is any issue with the configuration. I think the container is not reading the proc/mount, cgroup is empty in /proc/mounts/cgroup but is available at /cgroup/

**Comment by jangaraj** [comment]
I don't see debug output, because `-e "ZBX_DEBUGLEVEL=5"` is not supported in this image - https://github.com/monitoringartist/dockbix-agent-xxl#support

**Comment by maadjahangir** [comment]
Hey, Thanks for the response.

Hmm.. Maybe i am missing something here.  You are saying that ZBX_DEBUGLEVEL is not supported in the image and i imagine i cannot mount the configuration file as well.

So i might need to deploy it on the host instead of container to got the debug output. But again i think deploying on host wouldn't cause this problem.

Am i right here?

**Comment by jangaraj** [comment]
No, please read README - I'm pasting README URL again https://github.com/monitoringartist/dockbix-agent-xxl#support there is mentioned env variable for log level. README is your friend.

**Comment by maadjahangir** [comment]
@jangaraj Sigh.. Thanks for the reminder again. Didn't catch the difference in the first look. Anyways. Below is the debug output:

`[root@prod-central-monitoring ec2-user]# docker run --name=dockbix-agent-xxl --net=host --privileged -p 10050:10050 -h $(hostname) -v /:/rootfs  -v /var/run:/var/run --restart unless-stopped -e "ZA_Server=10.69.0.231" -e "ZA_ServerActive=10.69.0.231" -e "ZA_DebugLevel=4" --log-driver json-file -d monitoringartist/dockbix-agent-xxl-limited:latest
978217a7f621201bf104a5f816e2162b22c573aaf2746e3b71e6e8232a400f50
[root@prod-central-monitoring ec2-user]# docker logs -f dockbix-agent-xxl
Dockbix Agent XXL v0.0.1b limited version
Copyright (C) 2014-2017 Jan Garaj - www.monitoringartist.com
Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
Starting Zabbix Agent [monitoring]. Zabbix 3.2.4 Dockbix Agent XXL (2017-03-25) (revision ).
Press Ctrl+C to exit.

    14:20170508:081954.954 Starting Zabbix Agent [monitoring]. Zabbix 3.2.4 Dockbix Agent XXL (2017-03-25) (revision ).
    14:20170508:081954.954 **** Enabled features ****
    14:20170508:081954.954 IPv6 support:          YES
    14:20170508:081954.954 TLS support:            NO
    14:20170508:081954.954 **************************
    14:20170508:081954.954 using configuration file: /etc/zabbix/zabbix_agentd.conf
    14:20170508:081954.954 In zbx_load_modules()
    14:20170508:081954.954 loading module "/var/lib/zabbix/modules/zabbix_module_docker.so"
    14:20170508:081954.954 In zbx_module_api_version()
    14:20170508:081954.954 In zbx_module_init()
    14:20170508:081954.954 zabbix_module_docker v0.6.6, compilation time: Mar 25 2017 10:05:16
    14:20170508:081954.954 In zbx_docker_dir_detect()
    14:20170508:081954.954 Cannot open /proc/mounts: [2] No such file or directory
    14:20170508:081954.954 In zbx_docker_api_detect()
    14:20170508:081954.954 In zbx_module_docker_socket_query()
    14:20170508:081954.954 Docker's socket query: GET /_ping HTTP/1.0
    14:20170508:081954.955 Docker's socket response: OK
    14:20170508:081954.955 Docker's socket works - extended docker metrics are available
    14:20170508:081954.955 In zbx_module_item_list()
    14:20170508:081954.955 In zbx_module_item_timeout()
    14:20170508:081954.955 cannot find "zbx_module_history_write_cbs()" function in module "zabbix_module_docker.so": /var/lib/zabbix/modules/zabbix_module_docker.so: undefined symbol: zbx_module_history_write_cbs
    14:20170508:081954.955 loading module "/var/lib/zabbix/modules/zabbix_module_stress.so"
    14:20170508:081954.955 cannot find "zbx_module_history_write_cbs()" function in module "zabbix_module_stress.so": /var/lib/zabbix/modules/zabbix_module_stress.so: undefined symbol: zbx_module_history_write_cbs
    14:20170508:081954.955 loaded modules: zabbix_module_docker.so, zabbix_module_stress.so
    14:20170508:081954.955 End of zbx_load_modules():SUCCEED
    14:20170508:081954.955 In init_collector_data()
    14:20170508:081954.955 In zbx_dshm_create() proj_id:112 size:0
    14:20170508:081954.955 End of zbx_dshm_create():SUCCEED shmid:-1
    14:20170508:081954.956 End of init_collector_data()
    14:20170508:081954.956 agent #0 started [main process]
    15:20170508:081954.956 agent #1 started [collector]
    15:20170508:081954.956 In init_cpu_collector()
    16:20170508:081954.956 agent #2 started [listener #1]
    16:20170508:081954.956 __zbx_zbx_setproctitle() title:'listener #1 [waiting for connection]'
    17:20170508:081954.956 agent #3 started [listener #2]
    17:20170508:081954.956 __zbx_zbx_setproctitle() title:'listener #2 [waiting for connection]'
    18:20170508:081954.956 agent #4 started [listener #3]
    15:20170508:081954.956 End of init_cpu_collector():SUCCEED
    18:20170508:081954.956 __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
    15:20170508:081954.956 __zbx_zbx_setproctitle() title:'collector [processing data]'
    15:20170508:081954.956 In update_cpustats()
    19:20170508:081954.956 agent #5 started [active checks #1]
    19:20170508:081954.956 In init_active_metrics()
    19:20170508:081954.956 buffer: first allocation for 100 elements
    19:20170508:081954.956 End of init_active_metrics()
    19:20170508:081954.956 In send_buffer() host:'10.69.0.231' port:10051 entries:0/100
    19:20170508:081954.956 End of send_buffer():SUCCEED
    19:20170508:081954.956 __zbx_zbx_setproctitle() title:'active checks #1 [getting list of active checks]'
    19:20170508:081954.956 In refresh_active_checks() host:'10.69.0.231' port:10051
    19:20170508:081954.956 sending [{"request":"active checks","host":"monitoring","host_metadata":"dockbix-agent-xxl"}]
    19:20170508:081954.956 before read
    19:20170508:081954.958 got [{"response":"failed","info":"host [monitoring] not found"}]
    19:20170508:081954.958 In parse_list_of_checks()
    19:20170508:081954.958 no active checks on server [10.69.0.231:10051]: host [monitoring] not found
    19:20170508:081954.958 End of parse_list_of_checks():FAIL
    19:20170508:081954.958 End of refresh_active_checks():SUCCEED
    19:20170508:081954.958 __zbx_zbx_setproctitle() title:'active checks #1 [processing active checks]'
    19:20170508:081954.958 In process_active_checks() server:'10.69.0.231' port:10051
    15:20170508:081954.958 End of update_cpustats()
    19:20170508:081954.958 End of process_active_checks()
    15:20170508:081954.958 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
    19:20170508:081954.958 In get_min_nextcheck()
    19:20170508:081954.958 End of get_min_nextcheck():-1
    19:20170508:081954.958 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
    15:20170508:081955.958 __zbx_zbx_setproctitle() title:'collector [processing data]'
    19:20170508:081955.958 In send_buffer() host:'10.69.0.231' port:10051 entries:0/100
    19:20170508:081955.958 End of send_buffer():SUCCEED
    15:20170508:081955.958 In update_cpustats()
    19:20170508:081955.958 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
    15:20170508:081955.960 End of update_cpustats()
    15:20170508:081955.960 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
    19:20170508:081956.959 In send_buffer() host:'10.69.0.231' port:10051 entries:0/100
    19:20170508:081956.959 End of send_buffer():SUCCEED
    19:20170508:081956.959 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
    15:20170508:081956.960 __zbx_zbx_setproctitle() title:'collector [processing data]'
    15:20170508:081956.960 In update_cpustats()
    15:20170508:081956.961 End of update_cpustats()
    15:20170508:082028.006 In update_cpustats()
    15:20170508:082028.007 End of update_cpustats()`

**Comment by maadjahangir** [comment]
@jangaraj Have you got a chance to check this issue?

**Comment by jangaraj** [comment]
Nope. I need to replicate your env = I need to provision Amazon Linux AMI 2016.09 test VM.

**Comment by maadjahangir** [comment]
@jangaraj Any update?

**Comment by jangaraj** [comment]
Nope. @maadjahangir Are you able to provide test machine with your config?

**Comment by jangaraj** [comment]
Closing.

No user response and Dockbix works fine with Amazon Linux 2017 (I'm not able to test 2016):
```
[root@ip-10-0-8-12 ~]# docker run   --name=dockbix-agent-xxl   --net=host   --privileged   -v /:/rootfs   -v /var/run:/var/run   --restart unless-stopped   -e "ZA_Server=<ZABBIX SERVER IP/DNS NAME>"   -e "ZA_ServerActive=<ZABBIX SERVER IP/DNS NAME>" -e PROOT_NO_SECCOMP=1   -d monitoringartist/dockbix-agent-xxl-limited:latest
8c850f9735e5693db86d9598a58d467f9fdbdca7bf1737541f7d33637b796161
[root@ip-10-0-8-12 ~]# docker logs -f dockbix-agent-xxl
Dockbix Agent XXL v0.0.4b limited version
Docker image: monitoringartist/dockbix-agent-xxl-limited
Copyright (C) 2014-2017 Jan Garaj - www.monitoringartist.com
Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
Securing container
Starting Zabbix Agent [ip-10-0-8-12]. Zabbix 3.2.6 Dockbix Agent XXL (2017-07-10) (revision ).
Press Ctrl+C to exit.

     8:20170815:164359.385 Starting Zabbix Agent [ip-10-0-8-12]. Zabbix 3.2.6 Dockbix Agent XXL (2017-07-10) (revision ).
     8:20170815:164359.385 **** Enabled features ****
     8:20170815:164359.385 IPv6 support:          YES
     8:20170815:164359.385 TLS support:            NO
     8:20170815:164359.385 **************************
     8:20170815:164359.385 using configuration file: /etc/zabbix/zabbix_agentd.conf
     8:20170815:164359.388 loaded modules: zabbix_module_docker.so, zabbix_module_stress.so, zabbix_module_systemd.so, zabbix_module_sockets.so
     8:20170815:164359.389 agent #0 started [main process]
    13:20170815:164359.390 agent #5 started [active checks #1]
    12:20170815:164359.390 agent #4 started [listener #3]
    11:20170815:164359.391 agent #3 started [listener #2]
    10:20170815:164359.391 agent #2 started [listener #1]
     9:20170815:164359.391 agent #1 started [collector]
    13:20170815:164359.438 active check configuration update from [<ZABBIX SERVER IP/DNS NAME>:10051] started to fail (cannot resolve [<ZABBIX SERVER IP/DNS NAME>])
^C
[root@ip-10-0-8-12 ~]# docker exec -ti dockbix-agent-xxl zabbix_get -s 127.0.0.1 -k docker.mem[/dockbix-agent-xxl,rss]
2998272
[root@ip-10-0-8-12 ~]# docker exec -ti dockbix-agent-xxl zabbix_get -s 127.0.0.1 -k docker.cpu[/dockbix-agent-xxl,user]
1
[root@ip-10-0-8-12 ~]# docker exec -ti dockbix-agent-xxl zabbix_get -s 127.0.0.1 -k docker.discovery
{"data":[{"{#FCONTAINERID}":"8c850f9735e5693db86d9598a58d467f9fdbdca7bf1737541f7d33637b796161","{#SCONTAINERID}":"8c850f9735e5","{#SYSTEM.HOSTNAME}":"ip-10-0-8-12","{#HCONTAINERID}":"dockbix-agent-xxl"}]}
[root@ip-10-0-8-12 ~]# uname -a
Linux ip-10-0-8-12 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jjacobson93** [comment]
I'm having the same issue although it is happening intermittently: sometimes it will start up without the `/proc/mounts` no such file or directory error. We are running one agent on each host (running Ubuntu 16.04) in our Rancher environment.

I've attempted restarting the problem agents, which results in this error:
`Error #12 - problem during agent execution`

Deleting the container and starting a new one is the only way to prevent that error.

On the agents that don't have the issue, I end up getting:
`Cannot find the [Id] item in the received JSON object`

This error also occurs in agents, regardless of whether or not `/proc/mounts` is found:
`Remote command [who | wc -l] result is not unsigned integer`

**Docker Compose Configuration:**
```yaml
zabbix-agent:
    privileged: true
    image: monitoringartist/dockbix-agent-xxl-limited
    environment:
      ZA_Server: zabbix-server
      PROOT_NO_SECCOMP: '1'
    volumes:
    - /var/run:/var/run
    - /:/rootfs
    links:
    - server:zabbix-server
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
```

**Docker info:** (from one of the hosts)
```
Containers: 28
 Running: 23
 Paused: 0
 Stopped: 5
Images: 41
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 316
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local rancher-efs rancher-nfs
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1020-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795GiB
Name: host3
ID: CWPS:PF7R:U2GA:JZZ5:3ICH:6ULZ:4XMU:LYXI:PAXV:YQW2:WJI2:YVLA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=amazonec2
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Logs:**
```
8/24/2017 11:51:47 AM Dockbix Agent XXL v0.0.4b limited version
8/24/2017 11:51:47 AM Docker image: monitoringartist/dockbix-agent-xxl-limited
8/24/2017 11:51:47 AM Copyright (C) 2014-2017 Jan Garaj - www.monitoringartist.com
8/24/2017 11:51:47 AM Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
8/24/2017 11:51:47 AM Securing container
8/24/2017 11:51:47 AM Starting Zabbix Agent [zabbix-test-zabbix-agent-3]. Zabbix 3.2.6 Dockbix Agent XXL (2017-07-10) (revision ).
8/24/2017 11:51:47 AM Press Ctrl+C to exit.
8/24/2017 11:51:47 AM 
8/24/2017 11:51:47 AM     15:20170824:185147.179 Starting Zabbix Agent [zabbix-test-zabbix-agent-3]. Zabbix 3.2.6 Dockbix Agent XXL (2017-07-10) (revision ).
8/24/2017 11:51:47 AM     15:20170824:185147.179 **** Enabled features ****
8/24/2017 11:51:47 AM     15:20170824:185147.179 IPv6 support:          YES
8/24/2017 11:51:47 AM     15:20170824:185147.179 TLS support:            NO
8/24/2017 11:51:47 AM     15:20170824:185147.179 **************************
8/24/2017 11:51:47 AM     15:20170824:185147.179 using configuration file: /etc/zabbix/zabbix_agentd.conf
8/24/2017 11:51:47 AM     15:20170824:185147.179 Cannot open /proc/mounts: [2] No such file or directory
8/24/2017 11:51:47 AM     15:20170824:185147.182 [systemd] cannot open /proc/mounts: [2] No such file or directory
8/24/2017 11:51:47 AM     15:20170824:185147.182 loaded modules: zabbix_module_docker.so, zabbix_module_stress.so, zabbix_module_systemd.so, zabbix_module_sockets.so
8/24/2017 11:51:47 AM     15:20170824:185147.183 agent #0 started [main process]
8/24/2017 11:51:47 AM     16:20170824:185147.183 agent #1 started [collector]
8/24/2017 11:51:47 AM     19:20170824:185147.183 agent #4 started [listener #3]
8/24/2017 11:51:47 AM     17:20170824:185147.184 agent #2 started [listener #1]
8/24/2017 11:51:47 AM     18:20170824:185147.184 agent #3 started [listener #2]
```

**Comment by jangaraj** [comment]
> Remote command [who | wc -l] result is not unsigned integer

Remote commands are not supported in limited version - I guess you have attached OS Linux template where this command is used (Number of logged users).

> Cannot find the [Id] item in the received JSON object
https://github.com/monitoringartist/dockbix-agent-xxl#support use debug mode and you will see what exactly is doing and what are values received from the Docker API.

I don't idea about your other issues.
