### ISSUE TITLE
Start cutting releases?

### ISSUE THREAD

**Issue by gregswift** [monitoringartist/zabbix-docker-monitoring#75]
Would it be possible to start cutting releases in some fashion?  I got back to working on the packaging for this an right now my easiest thing is to use a commit hash or just 'master' as a reference.

**Comment by gregswift** [comment]
and i'm using 'easiest' loosely

**Comment by jangaraj** [comment]
Can we use git tags? Example of my repo, where tags are used https://github.com/monitoringartist/zabbix-xxl/releases

**Comment by rackergs** [comment]
that would  be great

**Comment by jangaraj** [comment]
Done. Tagging has been started. First available tag is `v0.6.6`. Tag will be following version used in the code:
```
char    *m_version = "v0.6.6";
```

**Comment by rackergs** [comment]
nice! thanks
