### ISSUE TITLE
Template docker as host - no data for containers

### ISSUE THREAD

**Issue by aviramartac** [monitoringartist/zabbix-docker-monitoring#79]
After attaching the template to a host, containers are discovered and created correctly as hosts.

Unfortunately, I am getting no data from the containers themselves (no error anywhere, just no data). 
I am able to get data locally no problem using something like:

`docker exec -ti dockbix-agent-xxl zabbix_get -s 127.0.0.1 -k docker.mem[/my_docker,rss]
`

**Comment by jangaraj** [comment]
That template is not listed in the readme = it's there only for the reference and I don't guarantee that works. Feel free to fix that template and create pull request please. I'll be happy to review it.

**Comment by aviramartac** [comment]
The template is fine - my mistake was trying to use active checks on the discovered containers. It doesn't work because their host name obviously doesn't match the agent's. Passive checks work fine.

Thanks :)
