### ISSUE TITLE
 docker driver detection in module_zabbix_docker

### ISSUE THREAD

**Issue by bernapa0** [monitoringartist/zabbix-docker-monitoring#87]
Hello. I have a problem with the docker driver detection.

OS:
Linux hybryda 4.13.16-coreos-r2 #1 SMP Wed Dec 6 04:27:34 UTC 2017 x86_64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz GenuineIntel GNU/Linux

DOCKER:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.13.16-coreos-r2
Operating System: Container Linux by CoreOS 1576.4.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.4MiB
Name: hybryda
ID: DVKD:RLZL:3SIL:ITWF:3RER:UW5H:ZVAX:QEIK:ZDUG:YQMU:T6T5:3LWE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

ZABBIX:

Starting Zabbix Agent [zabbix_docker]. Zabbix 3.4.5 (revision 76340).
Press Ctrl+C to exit.

     1:20180112:092714.206 Starting Zabbix Agent [zabbix_docker]. Zabbix 3.4.5 (revision 76340).
     1:20180112:092714.206 **** Enabled features ****
     1:20180112:092714.206 IPv6 support:          YES
     1:20180112:092714.207 TLS support:           YES
     1:20180112:092714.207 **************************
     1:20180112:092714.207 using configuration file: /usr/local/zabbix/etc/zabbix_agentd.conf
     1:20180112:092714.207 In zbx_load_modules()
     1:20180112:092714.207 loading module "/usr/local/zabbix//lib//zabbix_module_docker.so"
     1:20180112:092714.207 In zbx_module_api_version()
     1:20180112:092714.207 In zbx_module_init()
     1:20180112:092714.207 zabbix_module_docker v0.6.8, compilation time: Jan 12 2018 09:26:16
     1:20180112:092714.207 In zbx_docker_dir_detect()
     1:20180112:092714.207 Detected docker stat directory: /sys/fs/cgroup/
     1:20180112:092714.207 **Cannot detect used docker driver**
     1:20180112:092714.207 In zbx_docker_api_detect()
     1:20180112:092714.207 In zbx_module_docker_socket_query()
     1:20180112:092714.207 Docker's socket query: GET /_ping HTTP/1.0
     1:20180112:092714.207 Docker's socket response: OK
     1:20180112:092714.207 Docker's socket works - extended docker metrics are available

**Comment by jangaraj** [comment]
Yes, it should be solved as a part of #85. That part needs improvement.

**Comment by bernapa0** [comment]
Press Ctrl+C to exit.
     1:20180116:125128.292 Starting Zabbix Agent [zabbix_docker]. Zabbix 3.4.5 (revision 76340).
     1:20180116:125128.292 **** Enabled features ****
     1:20180116:125128.292 IPv6 support:          YES
     1:20180116:125128.292 TLS support:           YES
     1:20180116:125128.292 **************************
     1:20180116:125128.292 using configuration file: /usr/local/zabbix/etc/zabbix_agentd.conf
     1:20180116:125128.292 In zbx_load_modules()
     1:20180116:125128.292 loading module "/usr/local/zabbix//lib//zabbix_module_docker.so"
     1:20180116:125128.292 In zbx_module_api_version()
     1:20180116:125128.292 In zbx_module_init()
     1:20180116:125128.292 zabbix_module_docker v0.6.9, compilation time: Jan 16 2018 12:49:12
     1:20180116:125128.292 In zbx_docker_dir_detect()
     1:20180116:125128.298 Detected docker stat directory: /sys/fs/cgroup/
     1:20180116:125128.298 Cannot detect used docker driver
     1:20180116:125128.298 In zbx_docker_api_detect()
     1:20180116:125128.298 In zbx_module_docker_socket_query()
     1:20180116:125128.298 Docker's socket query: GET /_ping HTTP/1.0
     1:20180116:125128.299 Docker's socket response: OK
     1:20180116:125128.299 Docker's socket works - extended docker metrics are available
     1:20180116:125128.299 In zbx_module_item_list()
     1:20180116:125128.299 In zbx_module_item_timeout()
     1:20180116:125128.299 cannot find "zbx_module_history_write_cbs()" function in module "zabbix_module_docker.so": /usr/local/zabbix//lib//zabbix_module_docker.so: u
ndefined symbol: zbx_module_history_write_cbs
     1:20180116:125128.299 loading module "/usr/local/zabbix//lib//libzbxsystemd.so"
     1:20180116:125128.299 [systemd] starting v3.4.5, compiled: Jan 16 2018 12:49:24
     1:20180116:125128.299 [systemd] in cgroup_dir_detect()
     1:20180116:125128.299 [systemd] detected cgroup mount directory: /sys/fs/cgroup/
     1:20180116:125128.299 [systemd] cpu_cgroup is cpuacct
     1:20180116:125128.299 [systemd] set timeout to 3000ms
     1:20180116:125128.299 cannot find "zbx_module_history_write_cbs()" function in module "libzbxsystemd.so": /usr/local/zabbix//lib//libzbxsystemd.so: undefined symbo
l: zbx_module_history_write_cbs
