### ISSUE TITLE
#HCONTAINERID and #SCONTAINERID have the same value in frontend

### ISSUE THREAD

**Issue by mariaczi** [monitoringartist/zabbix-docker-monitoring#90]
On discovery (`zabbix_agentd -t docker.discovery`) we have correct value for macro #HCONTAINERID and #SCONTAINERID but in frontend of zabbix we got the same value for this macros.
I checked it putting all macros in Description field.
Zabbix version 3.4.5
Docker version 17.03.2-ce

**Comment by jangaraj** [comment]
Did you use provided template - https://github.com/monitoringartist/zabbix-docker-monitoring/blob/master/template/Zabbix-Template-App-Docker.xml ?

**Comment by jangaraj** [comment]
Nope - https://github.com/monitoringartist/zabbix-docker-monitoring#available-metrics

Note: cid - container ID, two options are available:

   - full container ID (macro {#FCONTAINERID}), e.g. 2599a1d88f75ea2de7283cbf469ea00f0e5d42aaace95f90ffff615c16e8fade

**OR**

 - human name or short container ID (macros {#HCONTAINERID} or {#SCONTAINERID}) - prefix "/" must be used, e.g. /zabbix-server or /2599a1d88f75

So for example:
`docker.cpu[2599a1d88f75ea2de7283cbf469ea00f0e5d42aaace95f90ffff615c16e8fade,user]`
is equivalent of 
`docker.cpu[/2599a1d88f75,user]` or `docker.cpu[/containerhumanname,user]` -> module will try to expand used short container id (#SCONTAINERID) or human container name (#HCONTAINERID) into full container ID (#FCONTAINERID).

**Comment by mariaczi** [comment]
\# docker ps --format "table {{.ID}}\t{{.Status}}"
CONTAINER ID        STATUS
f345d3196969        Up About an hour
04a4da86dc84        Up 3 days
650fad137d18        Up 3 days
3063e1a931ee        Up 3 days
3c5f44761b9e        Up 3 days

\# docker inspect --format="{{.Id}}" 3c5f44761b9e
3c5f44761b9e3b586886eb3819856a24cb6e22faf1c3221cd9d935a5c0c01270

# zabbix_agentd -t docker.up[/3c5f44761b9e]
docker.up[/3c5f44761b9e]                      [u|1]
# zabbix_agentd -t docker.up[/3c5f44761b9e3b586886eb3819856a24cb6e22faf1c3221cd9d935a5c0c01270]
docker.up[/3c5f44761b9e3b586886eb3819856a24cb6e22faf1c3221cd9d935a5c0c01270] [u|1]

Eh, now it's work as you wrote. But earlier it can't. I will check it tomorrow once again if I got correct values for macros and back with feedback. Thanks for your time :)

**Comment by mariaczi** [comment]
I change key for "Item prototype" in "Container xxx is running" to have as is in template
![selection_017](https://user-images.githubusercontent.com/25037132/35556436-806e1272-05a2-11e8-9cfb-1a519a80f316.png)

I'm wait for discovery and after it in frontend i can see:
![selection_018](https://user-images.githubusercontent.com/25037132/35556491-aa28dd90-05a2-11e8-9608-50f81a9a8e2f.png)

![selection_019](https://user-images.githubusercontent.com/25037132/35556918-e7ac4d7c-05a3-11e8-9180-78057cfe339c.png)

When I check it manually on server, I have:
```
# zabbix_agentd -t docker.up[/04a4da86dc84]
docker.up[/04a4da86dc84]                      [u|1]

# docker inspect --format="{{.Id}}" 04a4da86dc84
04a4da86dc84f8238eb9b72e8d3e0665542d898a04e75c7775596c8e5b5bf01e

# zabbix_agentd -t docker.up[/04a4da86dc84f8238eb9b72e8d3e0665542d898a04e75c7775596c8e5b5bf01e]
docker.up[/04a4da86dc84f8238eb9b72e8d3e0665542d898a04e75c7775596c8e5b5bf01e] [u|1]

# docker ps --format "table {{.ID}}\t{{.Status}}"
CONTAINER ID        STATUS
52102a8b5dce        Up 15 hours
636c0a882f85        Up 16 hours
f345d3196969        Up 19 hours
**04a4da86dc84        Up 3 days**
3063e1a931ee        Up 4 days
3c5f44761b9e        Up 4 days
b32df8d0b4bd        Up 4 weeks
86b26a8d9855        Up 2 months
```

I add macros in Description field on "Container is running":
![selection_020](https://user-images.githubusercontent.com/25037132/35557005-24c0d192-05a4-11e8-8410-cf71f330661b.png)
In result I receive:
![selection_021](https://user-images.githubusercontent.com/25037132/35557174-9aaa3baa-05a4-11e8-9343-a66130759316.png)
It is not prepared image, it is screenshot from zabbix web panel :)

**Comment by jangaraj** [comment]
I don't understand. What is a problem?

**Comment by mariaczi** [comment]
For example:
When I run:
`# zabbix_agentd -t docker.discovery`
on the server when zabbix agent work, I get (one from all):
`"{#FCONTAINERID}":"b32df8d0b4bd41773eb4b59e275c5b4d02e54aa3514f1a7c97a657c7b17e5276","{#SCONTAINERID}":"b32df8d0b4bd","{#SYSTEM.HOSTNAME}":"hostname.eu","{#HCONTAINERID}":"loadbalancer_1"`
but in zabbix web frontend the value for macro \#HCONTAINERID and \#SCONTAINERID is the same and it is the short CONTAINERID, not the HCONTAINERID.

**Comment by jangaraj** [comment]
1.) Pls. test it from the zabbix server with the `zabbix_get` utility
2.) If you are using modified template, then support for that template is not in the scope of this project - pls use http://zabbix.org/wiki/Getting_help
3.) Pls use provided default Docker template and monitor device `play.monitoringartist.com`, just to see if it's working fine. That's a my public test Docker host:
```
$ zabbix_get -s play.monitoringartist.com -k docker.discovery
{"data":[{"{#FCONTAINERID}":"842a8251a6e88d30da4a5d58fae61525558b85b4f939436eaef5a9dd455a566c","{#SCONTAINERID}":"842a8251a6e8","{#SYSTEM.HOSTNAME}":"demo-monitoring-art","{#HCONTAINERID}":"dockbix-agent-xxl"},{"{#FCONTAINERID}":"25f595a29965221818471db9b9d096495638ee2b7c79a86e2aafaf63f828c064","{#SCONTAINERID}":"25f595a29965","{#SYSTEM.HOSTNAME}":"demo-monitoring-art","{#HCONTAINERID}":"grafana-xxl"}]}
```

**Comment by mariaczi** [comment]
For all results and test presented here I'm using your oryginal template from this repository.
zabbix_get command from the zabbix server:
```# zabbix_get -s 193.179.114.68 -k docker.discovery
{"data":[{"{#FCONTAINERID}":"3c5f44761b9e3b586886eb3819856a24cb6e22faf1c3221cd9d935a5c0c01270","{#HCONTAINERID}":"3c5f44761b9e","{#SCONTAINERID}":"3c5f44761b9e","{#SYSTEM.HOSTNAME}":"hostname.eu"}]}```

From your server everything is OK:
```# zabbix_get -s play.monitoringartist.com -k docker.discovery
{"data":[{"{#FCONTAINERID}":"842a8251a6e88d30da4a5d58fae61525558b85b4f939436eaef5a9dd455a566c","{#SCONTAINERID}":"842a8251a6e8","{#SYSTEM.HOSTNAME}":"demo-monitoring-art","{#HCONTAINERID}":"dockbix-agent-xxl"},{"{#FCONTAINERID}":"25f595a29965221818471db9b9d096495638ee2b7c79a86e2aafaf63f828c064","{#SCONTAINERID}":"25f595a29965","{#SYSTEM.HOSTNAME}":"demo-monitoring-art","{#HCONTAINERID}":"grafana-xxl"}]}```
so, how I can debug where is the problem? I should start a docker containers with extra options?

btw. Big thanks for your time and support. Best regards.

**Comment by jangaraj** [comment]
OK. I'm closing this issue. It's your configuration issue, which is not within the scope of this project.

**Comment by mariaczi** [comment]
For the others who could be have the same issue:
Despite the AllowRoot option on zabbix agent configuration I have set to "1" but zabbix agent was run as "zabbix" user (without root privileges) then it not having possibility to communicate with docker via their socket.
[When I doing this all tests, I have docker running as root.]

**Comment by thefactor82** [comment]
Sorry for writing in this Closed ticket, but I have the same problem of Mariaczi and I don't understand if I have a wrong configuration or something else that can be resolved with your help. Returned values in frontend for HCONTAINERID and SCONTAINERID are the same, instead of having the human readable name of the container. What I have to do to have the human readable name of the container in frontend?

**Comment by jangaraj** [comment]
HCONTAINERID and SCONTAINERID are the same when the agent doesn't have permission to use Docker API - https://github.com/monitoringartist/zabbix-docker-monitoring#additional-docker-permissions

**Comment by thefactor82** [comment]
Just the thing I was missing. Thanks a lot for your help!
