### ISSUE TITLE
no stat directory

### ISSUE THREAD

**Issue by maomaodai** [monitoringartist/zabbix-docker-monitoring#91]
hellow 
when i get status from zabbix-server

[root@monitor-101 ~]# zabbix_get -s 10.0.254.41 -k docker.mem[cache,rss]
**ZBX_NOTSUPPORTED: docker.mem metrics are not available at the moment - no stat directory**

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/zabbix-docker-monitoring#troubleshooting
