### ISSUE TITLE
Additional Permission of Zabbix agent are not detected. Docker's socket API is not available

### ISSUE THREAD

**Issue by miaofenk** [monitoringartist/zabbix-docker-monitoring#96]
Hi,

I tried to create a zabbix-agent pod under K8S environment with zabbix-module-docker.so loaded.

I have set privileged as True when creating the pods and set AllowRoot=True in zabbix-agent.conf. However, I still got the following prints. I have no idea what else should I set to access the permission. Could you please help to check this?

agent.conf
```
### Option: AllowRoot
#       Allow the agent to run as 'root'. If disabled and the agent is started by 'root', the agent
#       will try to switch to the user specified by the User configuration option instead.
#       Has no effect if started under a regular user.
#       0 - do not allow
#       1 - allow
#
# Mandatory: no
# Default:
AllowRoot=1

### Option: User
#       Drop privileges to a specific, existing user on the system.
#       Only has effect if run as 'root' and AllowRoot is disabled.
#
# Mandatory: no
# Default:
# User=zabbix
```

agent.log
```
   597:20180413:014558.202 In load_modules()
   597:20180413:014558.202 loading module "/usr/local/lib/zabbix/zabbix_module_docker.so"
   597:20180413:014558.203 In zbx_module_api_version()
   597:20180413:014558.203 In zbx_module_init()
   597:20180413:014558.203 zabbix_module_docker v0.6.9, compilation time: Apr 12 2018 09:50:48
   597:20180413:014558.203 In zbx_docker_dir_detect()
   597:20180413:014558.203 Detected docker stat directory: /sys/fs/cgroup/
   597:20180413:014558.203 Detected used docker driver dir: system.slice/
   597:20180413:014558.204 Detected systemd docker - prefix/suffix will be used
   597:20180413:014558.204 Detected JoinController cpu,cpuacct
   597:20180413:014558.204 In zbx_docker_api_detect()
   597:20180413:014558.204 In zbx_docker_perm()
   597:20180413:014558.204 Additional permission of Zabbix Agent are not detected - only basic docker metrics are available
```

Thanks!

**Comment by miaofenk** [comment]
The module is based on branch [cgroup parent].

**Comment by miaofenk** [comment]
It seems that there is no "docker" usergroup in zabbix-agent pod. The zabbix-agent image is based on RHEL base image.

**Comment by jangaraj** [comment]
1.) cgroup-parent branch is **WIP** (work in progress) - You have to write additional code there + you have to test it if you want to have that feature implemented

2.) This is an issue about Zabbix Docker module used in your own unsupported Docker image. You need really deep Docker/Kubernetes knowledge if you want to use it in your own Docker image. I support here only my solutions. Take a look at:
https://github.com/monitoringartist/dockbix-agent-xxl
https://github.com/monitoringartist/kubernetes-zabbix
