### ISSUE TITLE
fping package missing

### ISSUE THREAD

**Issue by tcs-ulli** [monitoringartist/zabbix-docker-monitoring#98]
so discovery services dont work, after installing it with 
yum install fping all is working

**Comment by jangaraj** [comment]
This is a C module, which doesn't require fping binary at all. I guess you have a problem with another project https://github.com/monitoringartist/dockbix-xxl, so please report issue there (please also provide steps to reproduce issue). BTW I'm not able to reproduce it:
```
$ docker run --rm -ti monitoringartist/dockbix-xxl bash
Using default tag: latest
latest: Pulling from monitoringartist/dockbix-xxl
Digest: sha256:07107d5a73ce5ce254afc1a0b073cc656d5878a6e2fe3f7e0dd4da307323d925
Status: Image is up to date for monitoringartist/dockbix-xxl:latest
$ fping 127.0.0.1
127.0.0.1 is alive
```
