### ISSUE TITLE
 missing trigger

### ISSUE THREAD

**Issue by amritihealthlabs** [monitoringartist/zabbix-docker-monitoring#99]
First of all would like to thank you for the awesome template created by you. Next i would like to point out "cannot see any trigger available with the template for the docker" is this the default behaviour for the template ???

**Comment by jangaraj** [comment]
It's not easy to create a trigger(s), which will match needs of all users. What is a good trigger in one case, can be a false positive trigger in another case. For example container down trigger is good for prod server, where you have long-term running containers, but it will create a lot of noise on the CI server, where containers are used only for building/testing for short time period.

Really, you as a user need to define your own triggers.
